// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Realistic seed data for the PDPP reference personal server.
 * Represents a seeded local account whose personal server
 * already has data before the reference flow starts — showing that the personal server
 * is a persistent store, not an on-demand scraper.
 */

export interface SeedAccount {
  full_name: string;
  id: string;
  is_verified: boolean;
  username: string;
}

export interface SeedPost {
  caption: string | null;
  comment_count: number;
  id: string;
  like_count: number;
  media_type: "IMAGE" | "VIDEO" | "CAROUSEL_ALBUM";
  shortcode: string;
  taken_at: string;
}

export interface SeedAdTargeting {
  advertisers: string[];
  categories: string[];
  record_id: string;
  topics: string[];
}

// ~106 realistic following accounts — mix of creators, brands, personal contacts
export const SEED_FOLLOWING: SeedAccount[] = [
  { full_name: "National Geographic", id: "25025320", is_verified: true, username: "natgeo" },
  { full_name: "Instagram", id: "9527", is_verified: true, username: "instagram" },
  { full_name: "Kevin Systrom", id: "3", is_verified: true, username: "kevin" },
  { full_name: "Taylor Swift", id: "302577", is_verified: true, username: "taylorswift" },
  { full_name: "Snoop Dogg", id: "12281", is_verified: true, username: "snoopdogg" },
  { full_name: "NASA", id: "200428992", is_verified: true, username: "nasa" },
  { full_name: "The New York Times", id: "167009509", is_verified: true, username: "nytimes" },
  { full_name: "Stripe", id: "5765028", is_verified: true, username: "stripe" },
  { full_name: "Linear", id: "29187493", is_verified: false, username: "linear" },
  { full_name: "Figma", id: "183012668", is_verified: true, username: "figma" },
  { full_name: "Vercel", id: "258061269", is_verified: false, username: "vercel" },
  { full_name: "Anthropic", id: "422931568", is_verified: false, username: "anthropic" },
  { full_name: "OpenAI", id: "544030737", is_verified: false, username: "openai" },
  { full_name: "Paul Graham", id: "7320543", is_verified: false, username: "paulg" },
  { full_name: "Sam Altman", id: "58611", is_verified: true, username: "sama" },
  { full_name: "Jack Dorsey", id: "9129", is_verified: true, username: "jack" },
  { full_name: "Elon Musk", id: "1284161", is_verified: true, username: "elonmusk" },
  { full_name: "Sundar Pichai", id: "1166413", is_verified: true, username: "sundarpichai" },
  { full_name: "Jessica Alba", id: "174119690", is_verified: true, username: "jessicaalba" },
  { full_name: "Kylie Jenner", id: "25025368", is_verified: true, username: "kyliejenner" },
  { full_name: "MrBeast", id: "460563723", is_verified: true, username: "mrbeast" },
  { full_name: "Marques Brownlee", id: "7824459", is_verified: true, username: "mkbhd" },
  { full_name: "Lex Fridman", id: "21938291", is_verified: true, username: "lexfridman" },
  { full_name: "Andrew Huberman", id: "44278982", is_verified: true, username: "hubermanlab" },
  { full_name: "the owner Ferriss", id: "320695120", is_verified: true, username: "timferriss" },
  { full_name: "Paulo Coelho", id: "79299064", is_verified: true, username: "paulocoelho" },
  { full_name: "Neil deGrasse Tyson", id: "55793", is_verified: true, username: "neiltyson" },
  { full_name: "Barack Obama", id: "7536", is_verified: true, username: "obama" },
  { full_name: "ESPN", id: "47269647", is_verified: true, username: "espn" },
  { full_name: "NBA", id: "29639178", is_verified: true, username: "nba" },
  { full_name: "FC Barcelona", id: "19610161", is_verified: true, username: "fcbarcelona" },
  { full_name: "Real Madrid C.F.", id: "18479", is_verified: true, username: "realmadrid" },
  { full_name: "Cristiano Ronaldo", id: "48029851", is_verified: true, username: "cristiano" },
  { full_name: "Leo Messi", id: "197807526", is_verified: true, username: "leomessi" },
  { full_name: "LeBron James", id: "8539862", is_verified: true, username: "kingjames" },
  { full_name: "WIRED", id: "29524236", is_verified: true, username: "wired" },
  { full_name: "The Verge", id: "1642911", is_verified: true, username: "theverge" },
  { full_name: "TechCrunch", id: "4177889", is_verified: false, username: "techcrunch" },
  { full_name: "Ars Technica", id: "9617533", is_verified: false, username: "arstechnica" },
  { full_name: "Max", id: "188201606", is_verified: true, username: "hbomax" },
  { full_name: "Netflix", id: "25024955", is_verified: true, username: "netflix" },
  { full_name: "Spotify", id: "5765822", is_verified: true, username: "spotify" },
  { full_name: "Apple", id: "17841400008460746", is_verified: true, username: "apple" },
  { full_name: "Google", id: "429047592", is_verified: true, username: "google" },
  { full_name: "Microsoft", id: "3214607", is_verified: true, username: "microsoft" },
  { full_name: "Notion", id: "244994040", is_verified: false, username: "notion" },
  { full_name: "Alex Chen", id: "1234567891", is_verified: false, username: "alex.chen.sf" },
  { full_name: "Priya Nair", id: "1234567892", is_verified: false, username: "priya.dev" },
  { full_name: "Marco Rossi", id: "1234567893", is_verified: false, username: "marco.builds" },
  { full_name: "Sarah Kim", id: "1234567894", is_verified: false, username: "sarah.ux" },
  { full_name: "David Osei", id: "1234567895", is_verified: false, username: "david.writes" },
  { full_name: "Julia Santos", id: "1234567896", is_verified: false, username: "julia.codes" },
  { full_name: "Raj Patel", id: "1234567897", is_verified: false, username: "raj.ventures" },
  { full_name: "Emma Wilson", id: "1234567898", is_verified: false, username: "emma.photo" },
  { full_name: "Carlos Rivera", id: "1234567899", is_verified: false, username: "carlos.design" },
  { full_name: "Nina Johansson", id: "1234567900", is_verified: false, username: "nina.creates" },
  { full_name: "Tom Bradley", id: "1234567901", is_verified: false, username: "tom.ships" },
  { full_name: "Yuki Tanaka", id: "1234567902", is_verified: false, username: "yuki.art" },
  { full_name: "Kate Morrison", id: "1234567903", is_verified: false, username: "kate.pm" },
  { full_name: "Felix Weber", id: "1234567904", is_verified: false, username: "felix.ai" },
  { full_name: "a person Lindström", id: "1234567905", is_verified: false, username: "a person.vc" },
  { full_name: "Ben Okafor", id: "1234567906", is_verified: false, username: "ben.infra" },
  { full_name: "Chloe Martin", id: "1234567907", is_verified: false, username: "chloe.writes" },
  { full_name: "James Park", id: "1234567908", is_verified: false, username: "james.growth" },
  { full_name: "Sofia García", id: "1234567909", is_verified: false, username: "sofia.founder" },
  { full_name: "Luke Thompson", id: "1234567910", is_verified: false, username: "luke.ml" },
  { full_name: "Mia Schneider", id: "1234567911", is_verified: false, username: "mia.product" },
  { full_name: "Oliver Hughes", id: "1234567912", is_verified: false, username: "oliver.sec" },
  { full_name: "Zoe Dubois", id: "1234567913", is_verified: false, username: "zoe.research" },
  { full_name: "Amir Hassan", id: "1234567914", is_verified: false, username: "amir.eng" },
  { full_name: "Lily Chen", id: "1234567915", is_verified: false, username: "lily.content" },
  { full_name: "Noah Björk", id: "1234567916", is_verified: false, username: "noah.startup" },
  { full_name: "Eva Müller", id: "1234567917", is_verified: false, username: "eva.data" },
  { full_name: "Ivan Petrov", id: "1234567918", is_verified: false, username: "ivan.builds" },
  { full_name: "Grace Yamamoto", id: "1234567919", is_verified: false, username: "grace.ux" },
  { full_name: "Henry Adeyemi", id: "1234567920", is_verified: false, username: "henry.protocol" },
  { full_name: "Iris Larsson", id: "1234567921", is_verified: false, username: "iris.photo" },
  { full_name: "Daniel Nkosi", id: "1234567922", is_verified: false, username: "daniel.crypto" },
  { full_name: "Maya Krishnan", id: "1234567923", is_verified: false, username: "maya.bio" },
  { full_name: "Ethan Clarke", id: "1234567924", is_verified: false, username: "ethan.web3" },
  { full_name: "Leila Ahmadi", id: "1234567925", is_verified: false, username: "leila.ops" },
  { full_name: "Oscar Fernández", id: "1234567926", is_verified: false, username: "oscar.3d" },
  { full_name: "Nora Andersen", id: "1234567927", is_verified: false, username: "nora.climate" },
  { full_name: "Ryan O'Brien", id: "1234567928", is_verified: false, username: "ryan.devrel" },
  { full_name: "Sophie Leclerc", id: "1234567929", is_verified: false, username: "sophie.brand" },
  { full_name: "Max Bergmann", id: "1234567930", is_verified: false, username: "max.infosec" },
  { full_name: "Ava Johansson", id: "1234567931", is_verified: false, username: "ava.writes" },
  { full_name: "Leo Tremblay", id: "1234567932", is_verified: false, username: "leo.api" },
  { full_name: "Isla MacLeod", id: "1234567933", is_verified: false, username: "isla.design" },
  { full_name: "Kai Nakamura", id: "1234567934", is_verified: false, username: "kai.devops" },
  { full_name: "Violet Kowalski", id: "1234567935", is_verified: false, username: "violet.pm" },
  { full_name: "Sam Okonkwo", id: "1234567936", is_verified: false, username: "sam.infra" },
  { full_name: "Mira Svensson", id: "1234567937", is_verified: false, username: "mira.ml" },
  { full_name: "Caleb Figueiredo", id: "1234567938", is_verified: false, username: "caleb.open" },
  { full_name: "Luna external person", id: "1234567939", is_verified: false, username: "luna.artist" },
  { full_name: "Eli Shapiro", id: "1234567940", is_verified: false, username: "eli.embedded" },
  { full_name: "Freya Nilsson", id: "1234567941", is_verified: false, username: "freya.health" },
  { full_name: "Hugo Renaud", id: "1234567942", is_verified: false, username: "hugo.lang" },
  { full_name: "Sera Inoue", id: "1234567943", is_verified: false, username: "sera.vc" },
  { full_name: "Finn Larsen", id: "1234567944", is_verified: false, username: "finn.builds" },
  { full_name: "Stella Moreau", id: "1234567945", is_verified: false, username: "stella.edu" },
  { full_name: "Jasper van der Berg", id: "1234567946", is_verified: false, username: "jasper.sound" },
  { full_name: "Penny Nguyen", id: "1234567947", is_verified: false, username: "penny.ops" },
  { full_name: "Rémy Dupont", id: "1234567948", is_verified: false, username: "remy.systems" },
  { full_name: "Wren Callahan", id: "1234567949", is_verified: false, username: "wren.photo" },
  { full_name: "Cole Adebayo", id: "1234567950", is_verified: false, username: "cole.protocol" },
];

// Generate posts over the past 6 months (before consent date — all should be time-gated away)
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const SEED_POSTS: SeedPost[] = [
  {
    caption: "Building something that makes data work for people, not the other way around.",
    comment_count: 42,
    id: "p001",
    like_count: 847,
    media_type: "IMAGE",
    shortcode: "CxA1b2c3d4",
    taken_at: daysAgo(180),
  },
  {
    caption: "Late night debugging sessions hit different when the bug turns out to be a semicolon 🙃",
    comment_count: 67,
    id: "p002",
    like_count: 1203,
    media_type: "IMAGE",
    shortcode: "CxB2c3d4e5",
    taken_at: daysAgo(172),
  },
  {
    caption: "If you own your data, you own your narrative. That's the whole point.",
    comment_count: 134,
    id: "p003",
    like_count: 2891,
    media_type: "IMAGE",
    shortcode: "CxC3d4e5f6",
    taken_at: daysAgo(161),
  },
  {
    caption: null,
    comment_count: 12,
    id: "p004",
    like_count: 445,
    media_type: "VIDEO",
    shortcode: "CxD4e5f6g7",
    taken_at: daysAgo(154),
  },
  {
    caption: "The internet was supposed to empower individuals. We're not done building that.",
    comment_count: 208,
    id: "p005",
    like_count: 3102,
    media_type: "CAROUSEL_ALBUM",
    shortcode: "CxE5f6g7h8",
    taken_at: daysAgo(143),
  },
  {
    caption: "Shipped something I'm genuinely proud of today. More soon.",
    comment_count: 91,
    id: "p006",
    like_count: 1876,
    media_type: "IMAGE",
    shortcode: "CxF6g7h8i9",
    taken_at: daysAgo(132),
  },
  {
    caption: "The best privacy isn't hiding — it's having control.",
    comment_count: 317,
    id: "p007",
    like_count: 4210,
    media_type: "IMAGE",
    shortcode: "CxG7h8i9j0",
    taken_at: daysAgo(121),
  },
  {
    caption: null,
    comment_count: 28,
    id: "p008",
    like_count: 672,
    media_type: "VIDEO",
    shortcode: "CxH8i9j0k1",
    taken_at: daysAgo(113),
  },
  {
    caption: "Consent that means something. Working on it.",
    comment_count: 156,
    id: "p009",
    like_count: 2341,
    media_type: "IMAGE",
    shortcode: "CxI9j0k1l2",
    taken_at: daysAgo(102),
  },
  {
    caption: "Three principles: transparency, control, portability. Simple to say. Hard to build.",
    comment_count: 421,
    id: "p010",
    like_count: 5678,
    media_type: "CAROUSEL_ALBUM",
    shortcode: "CxJ0k1l2m3",
    taken_at: daysAgo(94),
  },
  {
    caption: null,
    comment_count: 19,
    id: "p011",
    like_count: 523,
    media_type: "IMAGE",
    shortcode: "CxK1l2m3n4",
    taken_at: daysAgo(87),
  },
  {
    caption: "Your data tells a story. You should be the author.",
    comment_count: 267,
    id: "p012",
    like_count: 3891,
    media_type: "IMAGE",
    shortcode: "CxL2m3n4o5",
    taken_at: daysAgo(79),
  },
  {
    caption: "Protocol design is hard. Not because of the technical parts.",
    comment_count: 78,
    id: "p013",
    like_count: 1123,
    media_type: "VIDEO",
    shortcode: "CxM3n4o5p6",
    taken_at: daysAgo(71),
  },
  {
    caption: "Standards matter because they outlast any single product.",
    comment_count: 189,
    id: "p014",
    like_count: 2456,
    media_type: "IMAGE",
    shortcode: "CxN4o5p6q7",
    taken_at: daysAgo(62),
  },
  {
    caption: null,
    comment_count: 34,
    id: "p015",
    like_count: 891,
    media_type: "CAROUSEL_ALBUM",
    shortcode: "CxO5p6q7r8",
    taken_at: daysAgo(55),
  },
  {
    caption: "Data sovereignty is a technical problem. Glad people are finally treating it that way.",
    comment_count: 512,
    id: "p016",
    like_count: 6234,
    media_type: "IMAGE",
    shortcode: "CxP6q7r8s9",
    taken_at: daysAgo(46),
  },
  {
    caption: "Ship. Learn. Repeat. The protocol is getting sharper.",
    comment_count: 93,
    id: "p017",
    like_count: 1567,
    media_type: "IMAGE",
    shortcode: "CxQ7r8s9t0",
    taken_at: daysAgo(38),
  },
  {
    caption: null,
    comment_count: 22,
    id: "p018",
    like_count: 734,
    media_type: "VIDEO",
    shortcode: "CxR8s9t0u1",
    taken_at: daysAgo(31),
  },
  {
    caption: "The consent screen is the most important UX on the internet. Nobody treats it that way.",
    comment_count: 678,
    id: "p019",
    like_count: 8901,
    media_type: "IMAGE",
    shortcode: "CxS9t0u1v2",
    taken_at: daysAgo(23),
  },
  {
    caption: "v0.1. Rough around the edges. But the core is solid.",
    comment_count: 241,
    id: "p020",
    like_count: 3214,
    media_type: "IMAGE",
    shortcode: "CxT0u1v2w3",
    taken_at: daysAgo(15),
  },
  {
    caption: null,
    comment_count: 41,
    id: "p021",
    like_count: 912,
    media_type: "CAROUSEL_ALBUM",
    shortcode: "CxU1v2w3x4",
    taken_at: daysAgo(8),
  },
  {
    caption: "Every data request should come with: who, what, why, how long. Non-negotiable.",
    comment_count: 334,
    id: "p022",
    like_count: 4523,
    media_type: "IMAGE",
    shortcode: "CxV2w3x4y5",
    taken_at: daysAgo(3),
  },
];

export const SEED_AD_TARGETING: SeedAdTargeting = {
  advertisers: [
    "GitHub",
    "JetBrains",
    "Digital Ocean",
    "AWS",
    "Notion",
    "Figma",
    "Linear",
    "Vercel",
    "Datadog",
    "Cloudflare",
    "Stripe",
    "Shopify",
    "MongoDB",
    "HashiCorp",
    "Twilio",
    "Retool",
    "Supabase",
    "PlanetScale",
    "Loom",
    "Pitch",
    "Arc Browser",
    "Raycast",
    "Posthog",
    "Sentry",
    "Segment",
  ],
  categories: [
    "Software & Technology",
    "Business & Industry",
    "Science & Education",
    "Arts & Crafts",
    "Travel & Tourism",
    "Health & Fitness",
    "News & Current Events",
  ],
  record_id: "ad_record_1",
  topics: [
    "Technology & Computing",
    "Software Development",
    "Artificial Intelligence",
    "Open Source",
    "Entrepreneurship",
    "Privacy & Security",
    "Venture Capital",
    "Product Design",
    "Cryptocurrency",
    "Science & Innovation",
  ],
};

// Profile data
export const SEED_PROFILE = {
  bio: "Building the personal data stack. Protocol nerd.",
  follower_count: 3847,
  following_count: SEED_FOLLOWING.length,
  full_name: "the owner",
  is_verified: false,
  profile_pic_url: "",
  username: "dondochaka",
};
