// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

// Pure data, deliberately split out of docs-source.ts: that module imports
// .source/server.ts (fumadocs-mdx, node:path) and is server-only, but
// components/specification/rail.tsx is a "use client" component that also needs
// to read these lists. Importing docs-source.ts from rail.tsx pulled the server
// module into the client bundle and failed the build (UnhandledSchemeError on
// node:path).

// The nav label is "Specification", so the route is /specification. A label and
// its URL that disagree read as two destinations; /docs is kept alive as a
// permanent redirect (see next.config.mjs) so every link already published
// still resolves.
export const docsRoute = "/specification";

// The unlisted index for everything that is NOT the specification. Nothing in
// the site's chrome links here: it is reached by typing the URL. See
// MAINTAINER_DOC_SLUGS.
export const maintainersRoute = "/maintainers";

// The specification IS the page. The rail lists the normative core, its
// companion specification, and the three extension profiles — the whole of what
// the protocol normatively defines, and nothing else.
//
// Order is the reading order of the specification set, not alphabetical.
export const PRIMARY_SLUGS = [
  "spec-core",
  "spec-discovery-and-trust",
  "spec-collection-profile",
  "spec-ext-lexical-search",
  "spec-ext-aggregation",
  "spec-semantic-retrieval-extension",
] as const;

// Slugs sync-spec-docs.mjs generates from a root spec-*.md (that script's own
// SPECS list). It writes these as .mdx — not .md — so each page's <Callout>
// status banner parses as JSX instead of being dropped as a raw HTML block by
// CommonMark. Every other content/docs page (governance is generated too, but
// from GOVERNANCE.md, and is tracked separately below; reference-implementation*
// and open-questions are hand-authored) stays plain .md.
//
// Kept here, deliberately duplicating that script's SPECS list, rather than
// imported from it: sync-spec-docs.mjs is a build-time Node script, and this
// module is imported by "use client" components (see the file-level comment
// above) that cannot pull in a script written to run under Node's fs/path
// APIs. Anything that reads a slug's extension (the sitemap, page metadata,
// the self-host coverage table) reads it from here so the two lists cannot
// silently diverge in three different places instead of one.
export const GENERATED_MDX_SPEC_SLUGS = [
  "spec-architecture",
  "spec-auth-design",
  "spec-change-tracking",
  "spec-collection-profile",
  "spec-connector-ecosystem",
  "spec-core",
  "spec-data-query-api",
  "spec-deferred",
  "spec-discovery-and-trust",
] as const;

// The real on-disk extension for a content/docs page generated by
// sync-spec-docs.mjs, for slugs whose extension isn't already known some
// other way (the programme doc uses GOVERNANCE_SLUG directly instead).
export function specDocExtension(slug: string): "md" | "mdx" {
  return (GENERATED_MDX_SPEC_SLUGS as readonly string[]).includes(slug) ? "mdx" : "md";
}

// The canonical URL for the governance programme document.
//
// It is NOT /specification/governance. Those six documents are specifications
// under CSL-1.0 that change through the Community Specification process;
// governance is a programme document amended by a vote of Partners. Serving it
// from inside the specification route would imply one amendment route where
// there are two, and would undercut its own §1 clause that no status it
// defines is a conformance requirement.
//
// It is still authored as a fumadocs page under content/docs, because that is
// what gives it the TOC, the Copy Markdown affordance and search indexing the
// spec pages get (the search route indexes the fumadocs source and nothing
// else). fumadocs therefore also routes it at /specification/governance, which
// 308-redirects here — the same duplicate-URL fix spec-core already uses.
export const governanceRoute = "/governance";

// The slug of that page inside the fumadocs collection.
export const GOVERNANCE_SLUG = "governance";

// The canonical URL for the PDPP Principles, on the same terms as governance
// above: authored inside the fumadocs collection so it carries the TOC, the
// Copy Markdown affordance and search indexing, served at its own top-level
// route because it is a programme document rather than a specification.
// /specification/principles 308-redirects here.
export const principlesRoute = "/principles";

// The slug of that page inside the fumadocs collection.
export const PRINCIPLES_SLUG = "principles";

// Everything the repository carries that is not normative protocol text:
// guides, design rationale, architectural context, deferred concerns, open
// questions, and the superseded Data Query API.
//
// These are UNLISTED, not deleted and not private. Each keeps its
// /specification/<slug> URL, so every link already published still resolves and
// nobody needs credentials to read one. What they lose is visibility: no rail
// entry, no nav link, noindex, and robots-disallowed (see app/robots.ts), so
// they never compete with the specification for a reader's attention or a
// search result. The one place they are listed is /maintainers, which is itself
// unlinked and unindexed.
//
// The bar for this list is normativity, not usefulness — spec-connector-ecosystem
// and reference-implementation-examples are both genuinely useful, and both
// describe what implementations DO rather than what the protocol REQUIRES.
export const MAINTAINER_DOC_SLUGS = [
  "spec-architecture",
  "reference-implementation",
  "reference-implementation-examples",
  "spec-connector-ecosystem",
  "spec-auth-design",
  "spec-change-tracking",
  "spec-data-query-api",
  "spec-deferred",
  "open-questions",
] as const;
