// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Locks the committed, parser-derived browser-collector proof fixture.
 *
 * The reference-implementation deterministic proof
 * (`reference-implementation/test/browser-collector-ingest-proof.test.js`)
 * ingests Amazon records through the real device-exporter `browser_collector`
 * path. Those records must be the connector's OWN output, not a hand-authored
 * shape — but the RI tsconfig (lib: ES2023, no DOM) cannot type-check the
 * DOM-dependent connector parsers, so the RI test cannot import them directly.
 *
 * This test lives in the polyfill-connectors package (whose tsconfig has DOM
 * lib), runs the real parsers over the committed, already-scrubbed DOM fixture,
 * and asserts the result EXACTLY matches the committed JSON the RI test reads
 * (`reference-implementation/test/fixtures/amazon-browser-collector-proof-records.json`).
 * If the parsers or record builders drift, this test fails and the JSON must be
 * regenerated (set `PDPP_REGEN_PROOF_FIXTURE=1`), keeping the RI proof's input
 * faithful to the connector without coupling the two packages' type programs.
 *
 * The fixture carries only scrubbed/synthetic data (the source DOM uses
 * `[REDACTED_NAME]` / `[REDACTED_ADDRESS]` and synthetic ASINs/order id).
 */

import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import {
  buildOrderItemRecord,
  buildOrderRecord,
  mergeOrderItems,
  parseOrderDate,
  parseOrdersListDom,
} from "./parsers.ts";
import type { OrderItemRecord, OrdersRecord } from "./types.ts";

const SCRUBBED_ORDERS_DOM = new URL(
  "../../fixtures/amazon/scrubbed/pilot-real-shape/dom/orders-list-2026.html",
  import.meta.url
);
const PROOF_RECORDS_JSON = new URL(
  "../../../../reference-implementation/test/fixtures/amazon-browser-collector-proof-records.json",
  import.meta.url
);
const EMITTED_AT = "2026-06-01T00:00:00.000Z";

interface ProofIngestRecord {
  data: OrdersRecord | OrderItemRecord;
  emitted_at: string;
  record_key: string;
  stream: string;
}

interface ProofFixture {
  _comment: string;
  emitted_at: string;
  records: ProofIngestRecord[];
  source_dom: string;
}

// Derive the device-exporter ingest records the real Amazon connector emits
// from the committed scrubbed orders-list DOM. Detail enrichment is null (the
// pilot fixture is a list page only), matching what the connector emits when it
// skips per-order detail.
function deriveProofFixture(): ProofFixture {
  const html = readFileSync(SCRUBBED_ORDERS_DOM, "utf8");
  const orders = parseOrdersListDom(html);
  const records: ProofIngestRecord[] = [];
  for (const listOrder of orders) {
    const orderDate = parseOrderDate(listOrder.orderDateRaw);
    if (!orderDate) {
      continue;
    }
    const orderRecord = buildOrderRecord(listOrder, null, orderDate, EMITTED_AT);
    records.push({
      stream: "orders",
      record_key: orderRecord.id,
      emitted_at: EMITTED_AT,
      data: orderRecord,
    });
    for (const merged of mergeOrderItems(listOrder, null)) {
      const itemRecord = buildOrderItemRecord(listOrder.orderId, orderDate, merged);
      records.push({
        stream: "order_items",
        record_key: itemRecord.id,
        emitted_at: EMITTED_AT,
        data: itemRecord,
      });
    }
  }
  return {
    _comment:
      "GENERATED by connectors/amazon/proof-ingest-records.test.ts from parseOrdersListDom + buildOrderRecord/buildOrderItemRecord over fixtures/amazon/scrubbed/pilot-real-shape/dom/orders-list-2026.html. Consumed by reference-implementation/test/browser-collector-ingest-proof.test.js. Regenerate with PDPP_REGEN_PROOF_FIXTURE=1. Scrubbed/synthetic data only.",
    emitted_at: EMITTED_AT,
    source_dom: "packages/polyfill-connectors/fixtures/amazon/scrubbed/pilot-real-shape/dom/orders-list-2026.html",
    records,
  };
}

function serialize(fixture: ProofFixture): string {
  return `${JSON.stringify(fixture, null, 2)}\n`;
}

test("committed browser-collector proof fixture matches the live Amazon parsers", () => {
  const derived = deriveProofFixture();
  assert.ok(derived.records.length > 0, "fixture must contain at least one record");
  assert.ok(
    derived.records.some((r) => r.stream === "orders") && derived.records.some((r) => r.stream === "order_items"),
    "fixture must exercise both Amazon streams"
  );

  const path = fileURLToPath(PROOF_RECORDS_JSON);
  if (process.env.PDPP_REGEN_PROOF_FIXTURE === "1") {
    writeFileSync(path, serialize(derived));
    return;
  }

  const committed = JSON.parse(readFileSync(path, "utf8")) as ProofFixture;
  assert.deepEqual(
    committed.records,
    derived.records,
    "committed proof fixture is stale; regenerate with PDPP_REGEN_PROOF_FIXTURE=1 (the connector parsers changed)"
  );
});

test("browser-collector proof fixture carries no un-scrubbed personal data", () => {
  const path = fileURLToPath(PROOF_RECORDS_JSON);
  const raw = readFileSync(path, "utf8");
  // The source DOM is scrubbed; the redaction markers must survive into the
  // derived records, and no obvious raw PII should appear.
  assert.ok(
    raw.includes("[REDACTED_NAME]") || raw.includes("[REDACTED_ADDRESS]"),
    "scrubbed redaction markers must survive into the derived records"
  );
});
