[program:cdp-proxy]
command=/usr/local/bin/cdp-proxy.py
autorestart=true
priority=850
stdout_logfile=/var/log/neko/cdp-proxy.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
redirect_stderr=true
