// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * SPIKE oracle comparison: hand-written `connectors/<c>/schemas.ts` vs the
 * generated `generated/<c>.schemas.gen.ts` (bin/generate-validators.ts).
 *
 * Targets: oura (no fixtures in this checkout — schema-vs-schema literal
 * comparison omitted for the fixture-driven assertion below) and jellyfin,
 * substituted for the requested "whoop" because this checkout has neither a
 * `manifests/whoop.json` nor a `connectors/whoop/` — verified absent before
 * substituting. Jellyfin was chosen as the second target because, like
 * oura, it ships both a manifest JSON Schema and a hand-written
 * `schemas.ts`, and — unlike oura — it also ships pilot-real-shape fixtures
 * (`fixtures/jellyfin/scrubbed/pilot-real-shape/records/*.jsonl`), which
 * this test needs for part (a). Oura's fixture directory does not exist in
 * this checkout (confirmed via `find fixtures/oura`), so oura is exercised
 * here only via `bin/generate-validators.ts` output inspection (see the
 * generated file itself + the written report), not through this fixture
 * oracle. Both connectors were generated by `bin/generate-validators.ts`
 * before this test file was written; run that command again if the
 * manifests change.
 *
 * Part (a) — ASSERTED: every record in jellyfin's pilot-real-shape fixture
 * must be accepted by BOTH validators.
 *
 * Part (b) — INFORMATIONAL ONLY: programmatic mutations (drop each required
 * field, wrong-type each field, null where disallowed, add an unexpected
 * field) are run through both validators and the agreement/disagreement
 * matrix is printed. Divergences are the spike's finding, not a failure.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import type { z } from "zod";
import { validateRecord as jellyfinValidateRecord } from "../connectors/jellyfin/schemas.ts";
import {
  itemsSchema as itemsSchemaGen,
  librariesSchema as librariesSchemaGen,
} from "../generated/jellyfin.schemas.gen.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(__dirname, "..");

type Verdict = { ok: true } | { ok: false; reason: string };

function verdictFromHandWritten(stream: string, data: Record<string, unknown>): Verdict {
  const result = jellyfinValidateRecord(stream, data);
  if (result.ok) {
    return { ok: true };
  }
  return { ok: false, reason: result.issues.map((i) => `${i.path}: ${i.message}`).join("; ") };
}

function verdictFromGenerated(schema: z.ZodTypeAny, data: Record<string, unknown>): Verdict {
  const result = schema.safeParse(data);
  if (result.success) {
    return { ok: true };
  }
  return { ok: false, reason: result.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ") };
}

const GENERATED_SCHEMAS: Record<string, z.ZodTypeAny> = {
  libraries: librariesSchemaGen,
  items: itemsSchemaGen,
};

function readJsonlRecords(stream: string): Record<string, unknown>[] {
  const path = join(PKG_ROOT, "fixtures", "jellyfin", "scrubbed", "pilot-real-shape", "records", `${stream}.jsonl`);
  return readFileSync(path, "utf8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as Record<string, unknown>);
}

// ─── Part (a): oracle agreement on real fixture records — ASSERTED ─────

for (const stream of ["libraries", "items"]) {
  test(`validator-gen spike (a): jellyfin/${stream} fixture records pass BOTH validators`, () => {
    const records = readJsonlRecords(stream);
    assert.ok(records.length > 0, `${stream}.jsonl must have ≥1 record`);

    const genSchema = GENERATED_SCHEMAS[stream];
    assert.ok(genSchema, `no generated schema registered for stream ${stream}`);

    const handFailures: string[] = [];
    const genFailures: string[] = [];
    for (const record of records) {
      const hand = verdictFromHandWritten(stream, record);
      if (!hand.ok) {
        handFailures.push(`id=${JSON.stringify(record.id)}: ${hand.reason}`);
      }
      const gen = verdictFromGenerated(genSchema, record);
      if (!gen.ok) {
        genFailures.push(`id=${JSON.stringify(record.id)}: ${gen.reason}`);
      }
    }
    assert.deepEqual(
      handFailures,
      [],
      `hand-written validator rejected real fixture records:\n${handFailures.join("\n")}`
    );
    assert.deepEqual(genFailures, [], `generated validator rejected real fixture records:\n${genFailures.join("\n")}`);
  });
}

// ─── Part (b): mutation agreement matrix — INFORMATIONAL ───────────────

interface MutationCase {
  data: Record<string, unknown>;
  kind: "drop-required" | "wrong-type" | "null-disallowed" | "add-unexpected" | "malformed-string";
  label: string;
}

const REQUIRED_BY_STREAM: Record<string, string[]> = {
  libraries: ["id", "name", "fetched_at"],
  items: ["id", "name", "library_id", "played", "play_count"],
};

// Deliberately wrong-typed replacement value per JSON type, keyed by the
// *correct* type so "wrong-type" always picks something incompatible.
function wrongTypeValueFor(correctSample: unknown): unknown {
  if (typeof correctSample === "string") {
    return 12_345;
  }
  if (typeof correctSample === "number") {
    return "not-a-number";
  }
  if (typeof correctSample === "boolean") {
    return "not-a-boolean";
  }
  if (Array.isArray(correctSample)) {
    return "not-an-array";
  }
  if (correctSample === null || typeof correctSample === "object") {
    return "not-an-object";
  }
  return 42;
}

function buildMutations(stream: string, base: Record<string, unknown>): MutationCase[] {
  const cases: MutationCase[] = [];
  const required = REQUIRED_BY_STREAM[stream] ?? [];

  // 1. Drop each required field.
  for (const field of required) {
    if (!(field in base)) {
      continue;
    }
    const mutated = { ...base };
    delete mutated[field];
    cases.push({ kind: "drop-required", label: `drop required "${field}"`, data: mutated });
  }

  // 2. Wrong-type each field present in the record.
  for (const [field, value] of Object.entries(base)) {
    const mutated = { ...base, [field]: wrongTypeValueFor(value) };
    cases.push({ kind: "wrong-type", label: `wrong-type "${field}"`, data: mutated });
  }

  // 3. Null where disallowed — pick fields whose real value is non-null and
  // set them to null. Whether this is "disallowed" is exactly what the
  // matrix is measuring (schema nullability may differ between validators).
  for (const [field, value] of Object.entries(base)) {
    if (value === null) {
      continue;
    }
    const mutated = { ...base, [field]: null };
    cases.push({ kind: "null-disallowed", label: `null "${field}"`, data: mutated });
  }

  // 4. Add an unexpected field.
  cases.push({
    kind: "add-unexpected",
    label: 'add unexpected "_unexpected_field"',
    data: { ...base, _unexpected_field: "surprise" },
  });

  // 5. Malformed-but-still-a-string values. This is distinct from
  // "wrong-type" (which swaps in a non-string) — it targets fields the
  // manifest types as bare `string`/`format: date|date-time` but where the
  // hand-written schema layers on a regex the generated schema cannot infer
  // from JSON Schema's `format` keyword alone (JSON Schema's `format` is
  // advisory, not a hard constraint, by spec default).
  for (const [field, value] of Object.entries(base)) {
    if (typeof value !== "string") {
      continue;
    }
    const mutated = { ...base, [field]: "not-a-well-formed-value!!" };
    cases.push({ kind: "malformed-string", label: `malformed-string "${field}"`, data: mutated });
  }

  return cases;
}

interface MatrixRow {
  agree: boolean;
  genOk: boolean;
  handOk: boolean;
  kind: string;
  label: string;
  stream: string;
}

test("validator-gen spike (b): mutation agreement matrix (informational, not asserted)", () => {
  const matrix: MatrixRow[] = [];

  for (const stream of ["libraries", "items"]) {
    const [base] = readJsonlRecords(stream);
    assert.ok(base, `${stream}.jsonl must have ≥1 record to build mutations from`);
    const genSchema = GENERATED_SCHEMAS[stream];
    assert.ok(genSchema, `no generated schema for stream ${stream}`);

    const mutations = buildMutations(stream, base);
    for (const m of mutations) {
      const hand = verdictFromHandWritten(stream, m.data);
      const gen = verdictFromGenerated(genSchema, m.data);
      matrix.push({
        stream,
        kind: m.kind,
        label: m.label,
        handOk: hand.ok,
        genOk: gen.ok,
        agree: hand.ok === gen.ok,
      });
    }
  }

  const agreeCount = matrix.filter((r) => r.agree).length;
  const disagreeCount = matrix.length - agreeCount;
  const byKind = new Map<string, { agree: number; disagree: number }>();
  for (const row of matrix) {
    const bucket = byKind.get(row.kind) ?? { agree: 0, disagree: 0 };
    if (row.agree) {
      bucket.agree += 1;
    } else {
      bucket.disagree += 1;
    }
    byKind.set(row.kind, bucket);
  }

  console.log("\n════════ validator-gen spike: mutation agreement matrix (jellyfin) ════════");
  console.log(`total cases: ${matrix.length}  agree: ${agreeCount}  disagree: ${disagreeCount}`);
  for (const [kind, counts] of byKind) {
    console.log(`  ${kind.padEnd(18)} agree=${counts.agree} disagree=${counts.disagree}`);
  }
  const divergences = matrix.filter((r) => !r.agree);
  if (divergences.length > 0) {
    console.log("\n  divergences (hand-written verdict vs generated verdict):");
    for (const row of divergences) {
      const handSide = row.handOk ? "ACCEPT" : "reject";
      const genSide = row.genOk ? "ACCEPT" : "reject";
      const relation = row.handOk && !row.genOk ? "hand-written LOOSER" : "hand-written STRICTER";
      console.log(`    [${row.stream}] ${row.label}: hand=${handSide} gen=${genSide}  (${relation})`);
    }
  }
  console.log("════════════════════════════════════════════════════════════════════════\n");

  // Informational only — this test always passes. The console output above
  // (captured in the spike report) is the actual finding.
  assert.ok(true);
});
