import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { COLLECTOR_PROTOCOL_VERSION } from '../server/collector-protocol.ts';
import { getDb } from '../server/db.js';
import { startServer } from '../server/index.js';

// ─── What this proves, and what it deliberately does NOT prove ───────────────
//
// This is the DETERMINISTIC, no-human half of the
// `add-browser-collector-enrollment-primitive` proof gate (tasks.md §3.4).
//
// It proves the *plumbing*: that a connector whose manifest declares a
// `browser` binding (Amazon) enrolls through the device-exporter path as a
// `browser_collector` instance, and that records shaped exactly like the ones
// the real Amazon connector emits flow through the real
// `/_ref/device-exporters/:id/ingest-batches` route, land in storage namespaced
// by `connector_instance_id`, and are queryable. The ingested records come from
// the committed fixture
// `test/fixtures/amazon-browser-collector-proof-records.json`, which is
// GENERATED by running the connector's OWN parsers
// (`parseOrdersListDom` → `buildOrderRecord` / `buildOrderItemRecord`) over the
// committed, already-scrubbed DOM fixture
// (`packages/polyfill-connectors/fixtures/amazon/scrubbed/pilot-real-shape/dom/orders-list-2026.html`).
// That generation + a drift lock live in the polyfill-connectors package
// (`connectors/amazon/proof-ingest-records.test.ts`) because the connector
// parsers depend on DOM lib types this package's tsconfig does not provide;
// keeping the derivation there avoids dragging DOM-typed code into the RI type
// program while still pinning these records to the connector's real output. The
// fixture carries no real personal data (scrubbed `[REDACTED_*]` markers).
//
// It does NOT prove the live-browser half: that a real, logged-in Amazon
// browser session on the owner's machine produces those records. That step is
// owner-mediated and cannot be produced honestly in a no-human worktree (it
// needs a real provider login and possibly 2FA). The spec
// (`local-device-exporter-collection`: "Browser-bound connectors SHALL NOT
// advertise a real next step without committed proof") therefore keeps the
// owner-connection-intent `browser_bound` branch at `unsupported`. The live
// proof and the resulting intent flip (tasks.md §3.5) are gated on an
// owner-run live proof (the prior operator runbook doc was removed in LFDT
// curation; the setup plan stays proof-gated with no runbook path).
//
// Concretely: passing this test is NECESSARY but NOT SUFFICIENT to close task
// 14. It removes every server-side and record-shape unknown so the live proof
// is a short, well-scoped owner session rather than an open-ended integration.

const PROTOCOL_HEADERS = { 'X-PDPP-Collector-Protocol': COLLECTOR_PROTOCOL_VERSION };
const PROOF_RECORDS_FIXTURE = new URL('./fixtures/amazon-browser-collector-proof-records.json', import.meta.url);

async function closeServer(server) {
  server.asServer.closeAllConnections();
  server.rsServer.closeAllConnections();
  const closeOne = (srv) => new Promise((resolve) => {
    let settled = false;
    const t = setTimeout(() => { if (!settled) { settled = true; resolve(); } }, 2000);
    srv.close(() => { if (!settled) { settled = true; clearTimeout(t); resolve(); } });
  });
  await Promise.allSettled([closeOne(server.asServer), closeOne(server.rsServer)]);
}

async function withServer(fn) {
  const server = await startServer({ quiet: true, asPort: 0, rsPort: 0, dbPath: ':memory:' });
  const asUrl = `http://localhost:${server.asPort}`;
  try {
    await fn({ asUrl });
  } finally {
    await closeServer(server);
  }
}

async function postJson(url, body, headers = {}) {
  const resp = await fetch(url, {
    method: 'POST',
    headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify(body),
  });
  let parsed = null;
  try {
    parsed = await resp.json();
  } catch {}
  return { body: parsed, status: resp.status };
}

function authHeaders(deviceToken) {
  return { Authorization: `Bearer ${deviceToken}`, ...PROTOCOL_HEADERS };
}

async function registerAmazonConnector(asUrl) {
  const manifest = JSON.parse(
    readFileSync(new URL('../../packages/polyfill-connectors/manifests/amazon.json', import.meta.url), 'utf8'),
  );
  const resp = await fetch(`${asUrl}/connectors`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(manifest),
  });
  assert.ok(resp.status < 500, `register amazon: ${resp.status}`);
}

// Enroll a browser-bound connector through the real device-exporter path and
// assert the source kind the binding-aware enrollment derived.
async function enrollBrowserCollector(asUrl, localBindingName) {
  const codeResp = await postJson(`${asUrl}/_ref/device-exporters/enrollment-codes`, {
    connector_id: 'amazon',
    local_binding_name: localBindingName,
  });
  assert.equal(codeResp.status, 201, JSON.stringify(codeResp.body));
  const enrollResp = await postJson(
    `${asUrl}/_ref/device-exporters/enroll`,
    { enrollment_code: codeResp.body.enrollment_code },
    PROTOCOL_HEADERS,
  );
  assert.equal(enrollResp.status, 201, JSON.stringify(enrollResp.body));
  assert.equal(enrollResp.body.connector_id, 'amazon');
  return enrollResp.body;
}

// Load the parser-derived, scrubbed ingest records the real Amazon connector
// emits. The fixture is generated and drift-locked against the live connector
// parsers by `packages/polyfill-connectors/connectors/amazon/proof-ingest-records.test.ts`,
// so these are the connector's true output, not a hand-authored shape.
function buildScrubbedAmazonIngestRecords() {
  const fixture = JSON.parse(readFileSync(PROOF_RECORDS_FIXTURE, 'utf8'));
  assert.ok(Array.isArray(fixture.records) && fixture.records.length > 0, 'proof fixture must contain records');
  return fixture.records;
}

test('browser_collector enrollment + device-exporter ingest persists parser-derived Amazon records (deterministic plumbing proof)', async () => {
  await withServer(async ({ asUrl }) => {
    await registerAmazonConnector(asUrl);

    // 1) Binding-aware enrollment records this as a browser_collector instance.
    const device = await enrollBrowserCollector(asUrl, 'the owner-personal-amazon');
    const instanceRow = getDb()
      .prepare('SELECT source_kind, source_binding_json FROM connector_instances WHERE connector_instance_id = ?')
      .get(device.connector_instance_id);
    assert.equal(instanceRow.source_kind, 'browser_collector', 'a browser-bound connector must enroll as browser_collector');
    assert.notEqual(instanceRow.source_kind, 'local_device');
    assert.equal(JSON.parse(instanceRow.source_binding_json).kind, 'browser_collector');

    // 2) Heartbeat the browser-collector source instance (the real collector
    //    heartbeats before/after ingest; prove the path accepts it).
    const heartbeat = await postJson(
      `${asUrl}/_ref/device-exporters/${encodeURIComponent(device.device_id)}/heartbeat`,
      {
        connector_id: device.connector_id,
        source_instance_id: device.source_instance_id,
        status: 'healthy',
        records_pending: 0,
      },
      authHeaders(device.device_token),
    );
    assert.equal(heartbeat.status, 200, JSON.stringify(heartbeat.body));

    // 3) Ingest the parser-derived records through the real ingest route.
    const records = buildScrubbedAmazonIngestRecords();
    const orderCount = records.filter((r) => r.stream === 'orders').length;
    const itemCount = records.filter((r) => r.stream === 'order_items').length;
    assert.ok(orderCount >= 1 && itemCount >= 1, 'fixture must exercise both Amazon streams');

    const ingest = await postJson(
      `${asUrl}/_ref/device-exporters/${encodeURIComponent(device.device_id)}/ingest-batches`,
      {
        batch_id: 'amazon-proof-batch-1',
        batch_seq: 0,
        body_hash: 'amazon-proof-batch-1-hash',
        connector_id: device.connector_id,
        device_id: device.device_id,
        source_instance_id: device.source_instance_id,
        records,
      },
      authHeaders(device.device_token),
    );
    assert.equal(ingest.status, 201, JSON.stringify(ingest.body));
    assert.equal(ingest.body.status, 'accepted');
    assert.equal(ingest.body.connector_instance_id, device.connector_instance_id);
    assert.equal(ingest.body.accepted_record_count, records.length);

    // 4) Records are persisted under the canonical `amazon` key, namespaced by
    //    the browser_collector connector_instance_id, and queryable.
    const db = getDb();
    const orderRows = db
      .prepare(
        `SELECT record_key, record_json FROM records
          WHERE connector_id = ? AND connector_instance_id = ? AND stream = ?
          ORDER BY record_key`,
      )
      .all('amazon', device.connector_instance_id, 'orders');
    assert.equal(orderRows.length, orderCount, 'every order record must persist under this instance');
    const persistedOrder = JSON.parse(orderRows[0].record_json);
    assert.match(persistedOrder.id, /^\d{3}-\d{7}-\d{7}$/, 'order id must survive ingest with its real shape');
    assert.equal(typeof persistedOrder.order_total_cents, 'number');

    const itemRows = db
      .prepare(
        `SELECT record_key, record_json FROM records
          WHERE connector_id = ? AND connector_instance_id = ? AND stream = ?
          ORDER BY record_key`,
      )
      .all('amazon', device.connector_instance_id, 'order_items');
    assert.equal(itemRows.length, itemCount, 'every order_item record must persist under this instance');
    assert.ok(
      itemRows.every((row) => JSON.parse(row.record_json).order_id),
      'each item record must carry its parent order_id',
    );

    // 5) The ingested records carry NO real personal data — the committed
    //    fixture is scrubbed, and the parsers preserve the redaction markers
    //    rather than reconstructing names/addresses. This guards the
    //    "do not commit personal data" constraint at the proof boundary.
    const allRecordJson = [...orderRows, ...itemRows].map((row) => row.record_json).join('\n');
    assert.ok(allRecordJson.includes('[REDACTED_NAME]') || allRecordJson.includes('[REDACTED_ADDRESS]'),
      'scrubbed redaction markers must survive into stored records');

    // 6) Idempotent replay (the real collector retries batches) returns
    //    `replayed`, not a duplicate persist.
    const replay = await postJson(
      `${asUrl}/_ref/device-exporters/${encodeURIComponent(device.device_id)}/ingest-batches`,
      {
        batch_id: 'amazon-proof-batch-1',
        batch_seq: 0,
        body_hash: 'amazon-proof-batch-1-hash',
        connector_id: device.connector_id,
        device_id: device.device_id,
        source_instance_id: device.source_instance_id,
        records,
      },
      authHeaders(device.device_token),
    );
    assert.equal(replay.status, 200, JSON.stringify(replay.body));
    assert.equal(replay.body.status, 'replayed');

    const afterReplay = db
      .prepare(
        `SELECT COUNT(*) AS n FROM records WHERE connector_id = ? AND connector_instance_id = ?`,
      )
      .get('amazon', device.connector_instance_id);
    assert.equal(afterReplay.n, records.length, 'replay must not duplicate persisted records');
  });
});

test('a second Amazon browser_collector account ingests in its own isolated namespace', async () => {
  // Multi-account is correct by construction (design Decision 6): two
  // browser_collector bindings for `amazon` resolve to distinct instances, and
  // one account's records never bleed into the other's.
  await withServer(async ({ asUrl }) => {
    await registerAmazonConnector(asUrl);
    const personal = await enrollBrowserCollector(asUrl, 'the owner-personal-amazon');
    const shared = await enrollBrowserCollector(asUrl, 'shared-amazon');
    assert.notEqual(personal.connector_instance_id, shared.connector_instance_id);

    const records = buildScrubbedAmazonIngestRecords();
    const ingestFor = (device, batchId) =>
      postJson(
        `${asUrl}/_ref/device-exporters/${encodeURIComponent(device.device_id)}/ingest-batches`,
        {
          batch_id: batchId,
          batch_seq: 0,
          body_hash: `${batchId}-hash`,
          connector_id: device.connector_id,
          device_id: device.device_id,
          source_instance_id: device.source_instance_id,
          records,
        },
        authHeaders(device.device_token),
      );

    const ingestPersonal = await ingestFor(personal, 'amazon-personal-batch');
    assert.equal(ingestPersonal.status, 201, JSON.stringify(ingestPersonal.body));
    const ingestShared = await ingestFor(shared, 'amazon-shared-batch');
    assert.equal(ingestShared.status, 201, JSON.stringify(ingestShared.body));

    // The same connector-local record keys exist once per instance — neither
    // account overwrote the other.
    const rows = getDb()
      .prepare(
        `SELECT connector_instance_id, COUNT(*) AS n FROM records
          WHERE connector_id = 'amazon'
          GROUP BY connector_instance_id
          ORDER BY connector_instance_id`,
      )
      .all();
    assert.equal(rows.length, 2, 'each Amazon account must keep its own record namespace');
    assert.ok(rows.every((row) => row.n === records.length));
  });
});
