// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by `pnpm colors:generate`. Do not edit directly.

export const conceptColorSchemeNames = ["plum", "moss", "azure"] as const;

export const defaultConceptColorSchemeName = "azure" as const;
