// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Checked-in exact allowlist for the package-wide `lint/performance/noAwaitInLoops`
 * policy.
 *
 * Two-layer design. biome.jsonc deliberately keeps `noAwaitInLoops: "off"`
 * for `src/`, `bin/`, `bench/`, `connectors/` (its own comment explains why:
 * the package's dominant loop shapes are genuinely sequential) — that
 * override is NOT removed by this file and stays in effect for ordinary
 * `pnpm check`/`biome check` runs. This file is the independent second
 * layer: the sole sanctioned exception mechanism, checked by a dedicated
 * gate that re-enables the rule out-of-band. Every (path, line, column)
 * below is a specific, reviewed, genuinely intentional sequential await,
 * not an escape hatch.
 *
 * Enforcement: `scripts/check-no-await-in-loops-conformance.ts` (wired into
 * `pnpm verify` as `check:noAwaitInLoops-conformance`) re-runs Biome with
 * the rule forced back to "error" for its own invocation only and fails
 * the build on:
 *   1. any LIVE finding whose location is not listed here (a new sequential
 *      await was introduced and was never reviewed/categorized), and
 *   2. any LISTED row whose location Biome no longer flags (the code moved or
 *      changed shape — the exception is stale and must be re-reviewed, not
 *      silently carried forward).
 *
 * Every row is categorized by WHY it must stay sequential — never a generic
 * blanket rationale:
 *
 *   - ordered_browser_interaction: sequential Playwright action against the shared page/context
 *   - dependent_pagination: next request depends on the prior page's cursor/offset/response
 *   - bounded_retry_polling: retry/backoff/poll loop gated on the prior attempt's outcome
 *   - provider_pacing_backpressure: rate-limited/budget-gated external call
 *   - ordered_protocol_emission: Collection Profile protocol emission requiring in-order delivery
 *   - dependent_file_cursor: sequential file/dir walk, incremental byte-offset read, or one-way fs mutation
 *   - shared_mutable_accumulator: loop body mutates a shared accumulator the next iteration reads
 *   - test_assertion_sequencing: test drives/asserts an ordered per-case side effect
 *   - devtool_sequential_output: manual dev-tool script printing ordered per-item console output
 *
 * To add a new entry after a genuine, reviewed addition: run
 *   pnpm exec biome check --only=performance/noAwaitInLoops --max-diagnostics=1000 \
 *     --reporter=json . (with the rule flipped to "error" in a scratch biome.jsonc
 *   copy, or use scripts/check-no-await-in-loops-conformance.ts --dump-live to print
 *   the current live finding set) — then classify ONLY the new row(s) into the
 *   right category above and append them here. Do not regenerate the whole file.
 */

export type NoAwaitInLoopsReasonCategory =
  | "ordered_browser_interaction"
  | "dependent_pagination"
  | "bounded_retry_polling"
  | "provider_pacing_backpressure"
  | "ordered_protocol_emission"
  | "dependent_file_cursor"
  | "shared_mutable_accumulator"
  | "test_assertion_sequencing"
  | "devtool_sequential_output";

export interface NoAwaitInLoopsAllowlistEntry {
  readonly category: NoAwaitInLoopsReasonCategory;
  readonly column: number;
  readonly line: number;
  /** Short, site-specific note — the awaited call this row covers. */
  readonly note: string;
  readonly path: string;
}

export const NO_AWAIT_IN_LOOPS_ALLOWLIST: readonly NoAwaitInLoopsAllowlistEntry[] = [
  {
    path: "bench/claude-code-two-pass.ts",
    line: 215,
    column: 15,
    category: "devtool_sequential_output",
    note: "runLegacyBaseline(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 264,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 369,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 477,
    column: 13,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 539,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 613,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 645,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 679,
    column: 5,
    category: "dependent_file_cursor",
    note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 713,
    column: 5,
    category: "dependent_file_cursor",
    note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/amazon-privacy-probe.ts",
    line: 42,
    column: 7,
    category: "ordered_browser_interaction",
    note: "page.goto(): sequential Playwright action against the shared page/context",
  },
  {
    path: "bin/register-all.ts",
    line: 109,
    column: 7,
    category: "devtool_sequential_output",
    note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "bin/replay-pilot-fixtures.ts",
    line: 132,
    column: 15,
    category: "dependent_pagination",
    note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "bin/replay-schemas.ts",
    line: 229,
    column: 20,
    category: "dependent_pagination",
    note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 62,
    column: 20,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 155,
    column: 19,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 165,
    column: 19,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 172,
    column: 7,
    category: "dependent_file_cursor",
    note: "mkdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 696,
    column: 20,
    category: "ordered_browser_interaction",
    note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 699,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 734,
    column: 20,
    category: "ordered_browser_interaction",
    note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 871,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 889,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1259,
    column: 5,
    category: "dependent_pagination",
    note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1270,
    column: 7,
    category: "dependent_pagination",
    note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1455,
    column: 11,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1499,
    column: 11,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/integration.test.ts",
    line: 370,
    column: 21,
    category: "test_assertion_sequencing",
    note: "processListOrder(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/apple_photos/index.ts",
    line: 170,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_health/index.ts",
    line: 68,
    column: 9,
    category: "ordered_protocol_emission",
    note: "onRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1324,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1514,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1568,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2128,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2160,
    column: 21,
    category: "ordered_browser_interaction",
    note: "processAccountDownload(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2431,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 1173,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 1885,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 1994,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2040,
    column: 17,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2066,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2109,
    column: 17,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2138,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2182,
    column: 17,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2439,
    column: 19,
    category: "provider_pacing_backpressure",
    note: "fetchChatGptPressureProbeStatus(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3074,
    column: 19,
    category: "provider_pacing_backpressure",
    note: "fetchBatch(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3104,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3137,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3157,
    column: 11,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3353,
    column: 16,
    category: "provider_pacing_backpressure",
    note: "fetchConversationDetailWaitingOutCircuit(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3435,
    column: 16,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3587,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "recoverPendingConversationDetailGapPage(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3713,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3924,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversation(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/integration.test.ts",
    line: 3077,
    column: 5,
    category: "test_assertion_sequencing",
    note: "runConversationsAndMessagesStreams(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 390,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 501,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 540,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 675,
    column: 13,
    category: "dependent_file_cursor",
    note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 754,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 805,
    column: 13,
    category: "dependent_file_cursor",
    note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 885,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 916,
    column: 7,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 962,
    column: 5,
    category: "dependent_file_cursor",
    note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 996,
    column: 5,
    category: "dependent_file_cursor",
    note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1238,
    column: 17,
    category: "dependent_file_cursor",
    note: "readdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1359,
    column: 7,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1419,
    column: 5,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1452,
    column: 7,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1478,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitGatedInventoryStream(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1718,
    column: 29,
    category: "dependent_file_cursor",
    note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1741,
    column: 31,
    category: "dependent_file_cursor",
    note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1826,
    column: 26,
    category: "dependent_file_cursor",
    note: "scanChildSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/integration.test.ts",
    line: 83,
    column: 5,
    category: "test_assertion_sequencing",
    note: "processJsonlLine(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/local-jsonl-incremental.test.ts",
    line: 346,
    column: 8,
    category: "test_assertion_sequencing",
    note: "import(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/local-jsonl-incremental.test.ts",
    line: 713,
    column: 20,
    category: "test_assertion_sequencing",
    note: "makeAttachmentSource(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/codex/index.ts",
    line: 484,
    column: 20,
    category: "dependent_file_cursor",
    note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 497,
    column: 7,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 516,
    column: 20,
    category: "dependent_file_cursor",
    note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 556,
    column: 11,
    category: "dependent_file_cursor",
    note: "isDirectoryPath(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1682,
    column: 5,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1702,
    column: 7,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1764,
    column: 21,
    category: "ordered_protocol_emission",
    note: "resolveGatedInventoryRecords(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/rollout-stream.test.ts",
    line: 216,
    column: 7,
    category: "test_assertion_sequencing",
    note: "once(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/github/index.ts",
    line: 299,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 322,
    column: 5,
    category: "dependent_pagination",
    note: "ctx.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 378,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 403,
    column: 5,
    category: "dependent_pagination",
    note: "ctx.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 464,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 494,
    column: 5,
    category: "dependent_pagination",
    note: "ctx.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 683,
    column: 18,
    category: "ordered_protocol_emission",
    note: "emitPullRequestItem(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 725,
    column: 5,
    category: "dependent_pagination",
    note: "ctx.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 792,
    column: 20,
    category: "dependent_pagination",
    note: "drainPrSearchWindow(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 886,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 915,
    column: 5,
    category: "dependent_pagination",
    note: "ctx.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 573,
    column: 23,
    category: "ordered_protocol_emission",
    note: "deps.hydrateAttachment(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 598,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 620,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 743,
    column: 25,
    category: "ordered_protocol_emission",
    note: "processMessage(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 952,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 1578,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 1778,
    column: 18,
    category: "provider_pacing_backpressure",
    note: "processServedAttachmentRecoveryGap(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 2387,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_messages/index.ts",
    line: 471,
    column: 17,
    category: "dependent_pagination",
    note: "fetchChatMessages(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_messages/index.ts",
    line: 542,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 74,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 110,
    column: 5,
    category: "dependent_file_cursor",
    note: "ctx.progress(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 124,
    column: 7,
    category: "ordered_protocol_emission",
    note: "ctx.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 143,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 179,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_maps_data_portability/index.ts",
    line: 272,
    column: 20,
    category: "dependent_pagination",
    note: "collectResourceGroup(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 120,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 170,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 220,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 313,
    column: 20,
    category: "dependent_file_cursor",
    note: "buildPhotoRecordForFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 489,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 280,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 610,
    column: 20,
    category: "ordered_browser_interaction",
    note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 630,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 662,
    column: 20,
    category: "ordered_browser_interaction",
    note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 707,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 797,
    column: 22,
    category: "ordered_browser_interaction",
    note: "loadListPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 823,
    column: 7,
    category: "ordered_browser_interaction",
    note: "processListOrder(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/ical/index.ts",
    line: 56,
    column: 15,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/ical/index.ts",
    line: 76,
    column: 20,
    category: "ordered_protocol_emission",
    note: "fetchIcs(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ical/index.ts",
    line: 121,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ical/index.ts",
    line: 154,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitEventsFromSource(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 332,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 376,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 631,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "resolveAttachmentHydration(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/notion/index.ts",
    line: 199,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/notion/index.ts",
    line: 272,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/oura/index.ts",
    line: 149,
    column: 18,
    category: "dependent_pagination",
    note: "oura(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/oura/index.ts",
    line: 242,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/pocket/index.ts",
    line: 161,
    column: 21,
    category: "dependent_pagination",
    note: "fetchPocketPage(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/pocket/index.ts",
    line: 167,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 155,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 242,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 335,
    column: 9,
    category: "dependent_pagination",
    note: "collectStream(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/reddit/integration.test.ts",
    line: 334,
    column: 5,
    category: "test_assertion_sequencing",
    note: "collectStream(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/reddit/integration.test.ts",
    line: 376,
    column: 5,
    category: "test_assertion_sequencing",
    note: "collectStream(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1228,
    column: 20,
    category: "shared_mutable_accumulator",
    note: "refreshScopedArchive(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1326,
    column: 9,
    category: "shared_mutable_accumulator",
    note: "runRequestedStreams(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1557,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1561,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1566,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1761,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1798,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2030,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2054,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2062,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2070,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2111,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2460,
    column: 32,
    category: "dependent_file_cursor",
    note: "reclaimUploads(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/slack/slack-api.ts",
    line: 205,
    column: 18,
    category: "dependent_pagination",
    note: "slackApiPost(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/slack/slack-api.ts",
    line: 252,
    column: 18,
    category: "dependent_pagination",
    note: "slackApiGet(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 156,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 184,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 222,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 261,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 279,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 329,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/strava/index.ts",
    line: 173,
    column: 7,
    category: "dependent_pagination",
    note: "progressWithSignals(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/strava/index.ts",
    line: 189,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/twitter_archive/index.ts",
    line: 146,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/credit-card-billing-stats.test.ts",
    line: 204,
    column: 5,
    category: "test_assertion_sequencing",
    note: "deps.emitRecord(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 287,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 417,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 721,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 786,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1066,
    column: 7,
    category: "ordered_browser_interaction",
    note: "page.goto(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1614,
    column: 21,
    category: "bounded_retry_polling",
    note: "runSingleLadderAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1731,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1864,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2072,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2282,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2316,
    column: 5,
    category: "ordered_protocol_emission",
    note: "processPdfStatementRow(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2446,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2545,
    column: 7,
    category: "ordered_browser_interaction",
    note: "page(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/integration.test.ts",
    line: 603,
    column: 21,
    category: "test_assertion_sequencing",
    note: "driveExport(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 129,
    column: 9,
    category: "ordered_browser_interaction",
    note: "c.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 152,
    column: 9,
    category: "ordered_browser_interaction",
    note: "c.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 501,
    column: 5,
    category: "ordered_browser_interaction",
    note: "hydrateOneStatement(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/transactions-coverage.test.ts",
    line: 178,
    column: 7,
    category: "test_assertion_sequencing",
    note: "deps.emit(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 149,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 202,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 318,
    column: 17,
    category: "provider_pacing_backpressure",
    note: "uploadBlob(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 466,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitStateForCursor(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 507,
    column: 22,
    category: "dependent_file_cursor",
    note: "parseExportFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 707,
    column: 9,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 777,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 781,
    column: 9,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 847,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 910,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 981,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1043,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1094,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1151,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1162,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1267,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1358,
    column: 9,
    category: "dependent_pagination",
    note: "collectForBudget(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "src/adaptive-lane.ts",
    line: 428,
    column: 24,
    category: "bounded_retry_polling",
    note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/amazon.ts",
    line: 65,
    column: 15,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/amazon.ts",
    line: 68,
    column: 11,
    category: "ordered_browser_interaction",
    note: "el.isVisible(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 340,
    column: 7,
    category: "ordered_browser_interaction",
    note: "candidate.waitFor(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 529,
    column: 5,
    category: "bounded_retry_polling",
    note: "checkpoint(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 872,
    column: 5,
    category: "bounded_retry_polling",
    note: "page.waitForTimeout(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 858,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 907,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 974,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 1003,
    column: 16,
    category: "test_assertion_sequencing",
    note: "ensureHebSession(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 74,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 93,
    column: 19,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 96,
    column: 34,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 117,
    column: 19,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 120,
    column: 34,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 146,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 180,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 325,
    column: 21,
    category: "ordered_browser_interaction",
    note: "inspectPostSubmitAuthSurface(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 468,
    column: 20,
    category: "ordered_browser_interaction",
    note: "fillWhenUsable(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 482,
    column: 40,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 669,
    column: 22,
    category: "bounded_retry_polling",
    note: "waitForUniqueVerificationCodeFormRoot(): retry/poll until the remounted OTP surface is uniquely actionable",
  },
  {
    path: "src/auto-login/manual-action-copy.test.ts",
    line: 42,
    column: 17,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/reddit.test.ts",
    line: 94,
    column: 9,
    category: "bounded_retry_polling",
    note: "makeLocator().waitFor(): bounded test double polling until the simulated locator attaches",
  },
  {
    path: "src/auto-login/reddit.ts",
    line: 275,
    column: 10,
    category: "bounded_retry_polling",
    note: "hasSessionCookie(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 156,
    column: 19,
    category: "ordered_browser_interaction",
    note: "action.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 161,
    column: 18,
    category: "ordered_browser_interaction",
    note: "locator.isVisible(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 302,
    column: 18,
    category: "bounded_retry_polling",
    note: "requestOtp(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/browser-launch.ts",
    line: 516,
    column: 14,
    category: "bounded_retry_polling",
    note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/browser-launch.ts",
    line: 933,
    column: 24,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/browser-launch.ts",
    line: 1003,
    column: 16,
    category: "shared_mutable_accumulator",
    note: "closeRemoteDevToolsTarget(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/browser-launch.ts",
    line: 1011,
    column: 27,
    category: "shared_mutable_accumulator",
    note: "fetchRemoteDevToolsTargets(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/collector-registry.test.ts",
    line: 53,
    column: 33,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/collector-registry.test.ts",
    line: 70,
    column: 33,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/collector-runner.ts",
    line: 1700,
    column: 7,
    category: "provider_pacing_backpressure",
    note: "input.client.recoverLocalCollectorGap(): rate-limited/budget-gated external call",
  },
  {
    path: "src/collector-runner.ts",
    line: 2007,
    column: 7,
    category: "shared_mutable_accumulator",
    note: "drainClaimedOutboxItem(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/collector-runner.ts",
    line: 2507,
    column: 18,
    category: "shared_mutable_accumulator",
    note: "input.queue.dequeueReady(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 279,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 302,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 348,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g1.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-runtime-session-watchdog.test.ts",
    line: 152,
    column: 7,
    category: "test_assertion_sequencing",
    note: "watchdog.checkpoint(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-runtime.ts",
    line: 1283,
    column: 9,
    category: "shared_mutable_accumulator",
    note: "closeBrowserPage(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/http-retry.ts",
    line: 244,
    column: 5,
    category: "bounded_retry_polling",
    note: "beforeAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/interaction-handler.ts",
    line: 84,
    column: 7,
    category: "dependent_file_cursor",
    note: "access(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/interaction-handler.ts",
    line: 119,
    column: 21,
    category: "bounded_retry_polling",
    note: "promptStdin(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/local-device-runtime.ts",
    line: 222,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "queue.enqueue(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/local-device-runtime.ts",
    line: 286,
    column: 18,
    category: "shared_mutable_accumulator",
    note: "input.queue.dequeueReady(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 81,
    column: 27,
    category: "dependent_file_cursor",
    note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 182,
    column: 29,
    category: "dependent_file_cursor",
    note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 193,
    column: 9,
    category: "dependent_file_cursor",
    note: "onLine(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/profile-lock.ts",
    line: 132,
    column: 7,
    category: "dependent_file_cursor",
    note: "fs.unlink(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/reference-blob-uploader.test.ts",
    line: 39,
    column: 12,
    category: "test_assertion_sequencing",
    note: "reader.read(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/reference-blob-uploader.test.ts",
    line: 103,
    column: 5,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/scheduler-runner.ts",
    line: 253,
    column: 7,
    category: "devtool_sequential_output",
    note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "connectors/apple_contacts/bounded-response-read.ts",
    line: 86,
    column: 31,
    category: "dependent_file_cursor",
    note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/apple_contacts/carddav-client.ts",
    line: 60,
    column: 41,
    category: "dependent_pagination",
    note: "davRequest(): next redirect hop depends on the prior response's Location header",
  },
  {
    path: "connectors/apple_contacts/discovery.ts",
    line: 241,
    column: 17,
    category: "dependent_pagination",
    note: "propfindFollowingRedirects(): next redirect hop depends on the prior response's Location header",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 264,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 268,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 279,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 293,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 361,
    column: 42,
    category: "shared_mutable_accumulator",
    note: "collectAddressBook(): loop body mutates a shared bookCursor/newState accumulator the next iteration reads",
  },
  {
    path: "connectors/google_calendar/api.ts",
    line: 210,
    column: 29,
    category: "dependent_pagination",
    note: "listCalendars(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 167,
    column: 18,
    category: "dependent_pagination",
    note: "pageThroughEvents(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 183,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 270,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 294,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "collectGoogleCalendar(): loop body mutates a shared nextEventsState accumulator the next iteration reads",
  },
  {
    path: "connectors/google_contacts/api.ts",
    line: 289,
    column: 29,
    category: "dependent_pagination",
    note: "listContactGroups(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 164,
    column: 18,
    category: "dependent_pagination",
    note: "syncPeoplePages(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 176,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 257,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 167,
    column: 29,
    category: "dependent_file_cursor",
    note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 315,
    column: 17,
    category: "provider_pacing_backpressure",
    note: "normalizeOneAttachment(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 485,
    column: 9,
    category: "ordered_protocol_emission",
    note: 'emitRecord("groups"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/groupme/index.ts",
    line: 523,
    column: 5,
    category: "dependent_pagination",
    note: "collectGroupMessagesForGroup(): next request depends on the prior page's before_id cursor",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 544,
    column: 22,
    category: "provider_pacing_backpressure",
    note: "toGroupMessageRecord(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 570,
    column: 7,
    category: "shared_mutable_accumulator",
    note: "collectGroupMessages(): loop body mutates a shared groupMessageCursor accumulator the next iteration reads",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 604,
    column: 9,
    category: "ordered_protocol_emission",
    note: 'emitRecord("direct_messages"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/groupme/index.ts",
    line: 645,
    column: 5,
    category: "dependent_pagination",
    note: "collectDirectChatMessagesForChat(): next request depends on the prior page's before_id cursor",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 666,
    column: 22,
    category: "provider_pacing_backpressure",
    note: "toDirectChatMessageRecord(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 695,
    column: 7,
    category: "shared_mutable_accumulator",
    note: "collectDirectChatMessages(): loop body mutates a shared directChatMessageCursor accumulator the next iteration reads",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 438,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "collectItems(): loop body mutates shared state.items/totalItemsEmitted accumulator the next iteration reads",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 471,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitErrorSkipResults(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 107,
    column: 31,
    category: "dependent_file_cursor",
    note: "readBodyWithStreamingCap(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 338,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'emitRecord("libraries"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 375,
    column: 23,
    category: "dependent_pagination",
    note: "collectItemsForLibrary(): next request depends on the prior page's StartIndex cursor",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 403,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'emitRecord("items"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/netflix_export/index.ts",
    line: 287,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/netflix_export/parsers.ts",
    line: 162,
    column: 29,
    category: "dependent_file_cursor",
    note: "fd.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/steam/index.ts",
    line: 342,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'deps.emitRecord("owned_games"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/steam/index.ts",
    line: 388,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'deps.emitRecord("recently_played_games"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/steam/index.ts",
    line: 431,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'deps.emitRecord("friends"): Collection Profile protocol emission requiring in-order delivery',
  },
];
