// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Checked-in exact allowlist for the package-wide `lint/performance/noAwaitInLoops`
 * policy.
 *
 * Two-layer design. biome.jsonc deliberately keeps `noAwaitInLoops: "off"`
 * for `src/`, `bin/`, `bench/`, `connectors/` (its own comment explains why:
 * the package's dominant loop shapes are genuinely sequential) — that
 * override is NOT removed by this file and stays in effect for ordinary
 * `pnpm check`/`biome check` runs. This file is the independent second
 * layer: the sole sanctioned exception mechanism, checked by a dedicated
 * gate that re-enables the rule out-of-band. Every (path, line, column)
 * below is a specific, reviewed, genuinely intentional sequential await,
 * not an escape hatch.
 *
 * Enforcement: `scripts/check-no-await-in-loops-conformance.ts` (wired into
 * `pnpm verify` as `check:noAwaitInLoops-conformance`) re-runs Biome with
 * the rule forced back to "error" for its own invocation only and fails
 * the build on:
 *   1. any LIVE finding whose location is not listed here (a new sequential
 *      await was introduced and was never reviewed/categorized), and
 *   2. any LISTED row whose location Biome no longer flags (the code moved or
 *      changed shape — the exception is stale and must be re-reviewed, not
 *      silently carried forward).
 *
 * Every row is categorized by WHY it must stay sequential — never a generic
 * blanket rationale:
 *
 *   - ordered_browser_interaction: sequential Playwright action against the shared page/context
 *   - dependent_pagination: next request depends on the prior page's cursor/offset/response
 *   - bounded_retry_polling: retry/backoff/poll loop gated on the prior attempt's outcome
 *   - provider_pacing_backpressure: rate-limited/budget-gated external call
 *   - ordered_protocol_emission: Collection Profile protocol emission requiring in-order delivery
 *   - dependent_file_cursor: sequential file/dir walk, incremental byte-offset read, or one-way fs mutation
 *   - shared_mutable_accumulator: loop body mutates a shared accumulator the next iteration reads
 *   - test_assertion_sequencing: test drives/asserts an ordered per-case side effect
 *   - devtool_sequential_output: manual dev-tool script printing ordered per-item console output
 *
 * To add a new entry after a genuine, reviewed addition: run
 *   pnpm exec biome check --only=performance/noAwaitInLoops --max-diagnostics=1000 \
 *     --reporter=json . (with the rule flipped to "error" in a scratch biome.jsonc
 *   copy, or use scripts/check-no-await-in-loops-conformance.ts --dump-live to print
 *   the current live finding set) — then classify ONLY the new row(s) into the
 *   right category above and append them here. Do not regenerate the whole file.
 */

export type NoAwaitInLoopsReasonCategory =
  | "ordered_browser_interaction"
  | "dependent_pagination"
  | "bounded_retry_polling"
  | "provider_pacing_backpressure"
  | "ordered_protocol_emission"
  | "dependent_file_cursor"
  | "shared_mutable_accumulator"
  | "test_assertion_sequencing"
  | "devtool_sequential_output";

export interface NoAwaitInLoopsAllowlistEntry {
  readonly category: NoAwaitInLoopsReasonCategory;
  readonly column: number;
  readonly line: number;
  /** Short, site-specific note — the awaited call this row covers. */
  readonly note: string;
  readonly path: string;
}

export const NO_AWAIT_IN_LOOPS_ALLOWLIST: readonly NoAwaitInLoopsAllowlistEntry[] = [
  {
    path: "bench/claude-code-two-pass.ts",
    line: 215,
    column: 15,
    category: "devtool_sequential_output",
    note: "runLegacyBaseline(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 264,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 369,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 477,
    column: 13,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 539,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 613,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 645,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 679,
    column: 5,
    category: "dependent_file_cursor",
    note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bench/legacy/claude-code-pre-tranche-c.ts",
    line: 713,
    column: 5,
    category: "dependent_file_cursor",
    note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/amazon-privacy-probe.ts",
    line: 42,
    column: 7,
    category: "ordered_browser_interaction",
    note: "page.goto(): sequential Playwright action against the shared page/context",
  },
  {
    path: "bin/register-all.ts",
    line: 74,
    column: 7,
    category: "devtool_sequential_output",
    note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "bin/replay-pilot-fixtures.ts",
    line: 132,
    column: 15,
    category: "dependent_pagination",
    note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "bin/replay-schemas.ts",
    line: 229,
    column: 20,
    category: "dependent_pagination",
    note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 62,
    column: 20,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 155,
    column: 19,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 165,
    column: 19,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "bin/scrub-fixtures.ts",
    line: 172,
    column: 7,
    category: "dependent_file_cursor",
    note: "mkdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 811,
    column: 20,
    category: "ordered_browser_interaction",
    note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 821,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 856,
    column: 20,
    category: "ordered_browser_interaction",
    note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1043,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1101,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1509,
    column: 5,
    category: "dependent_pagination",
    note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1520,
    column: 7,
    category: "dependent_pagination",
    note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1709,
    column: 11,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/index.ts",
    line: 1759,
    column: 11,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/amazon/integration.test.ts",
    line: 377,
    column: 21,
    category: "test_assertion_sequencing",
    note: "processListOrder(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/apple_photos/index.ts",
    line: 170,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_health/index.ts",
    line: 68,
    column: 9,
    category: "ordered_protocol_emission",
    note: "onRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1400,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1590,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1644,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 1751,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): statement DETAIL_GAP emissions preserve source outcome order",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2228,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2260,
    column: 21,
    category: "ordered_browser_interaction",
    note: "processAccountDownload(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/chase/index.ts",
    line: 2549,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2451,
    column: 17,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 1194,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 1928,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2188,
    column: 5,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2474,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2564,
    column: 7,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2592,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2684,
    column: 7,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 2981,
    column: 19,
    category: "provider_pacing_backpressure",
    note: "fetchChatGptPressureProbeStatus(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3616,
    column: 19,
    category: "provider_pacing_backpressure",
    note: "fetchBatch(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3646,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3679,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3699,
    column: 11,
    category: "ordered_protocol_emission",
    note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3895,
    column: 16,
    category: "provider_pacing_backpressure",
    note: "fetchConversationDetailWaitingOutCircuit(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 3977,
    column: 16,
    category: "dependent_pagination",
    note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 4129,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "recoverPendingConversationDetailGapPage(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 4264,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/index.ts",
    line: 4461,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitConversation(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/chatgpt/integration.test.ts",
    line: 3828,
    column: 5,
    category: "test_assertion_sequencing",
    note: "runConversationsAndMessagesStreams(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 386,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 497,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 537,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 733,
    column: 13,
    category: "dependent_file_cursor",
    note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 817,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 866,
    column: 13,
    category: "dependent_file_cursor",
    note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 953,
    column: 5,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 984,
    column: 7,
    category: "dependent_file_cursor",
    note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1033,
    column: 5,
    category: "dependent_file_cursor",
    note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1067,
    column: 5,
    category: "dependent_file_cursor",
    note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1345,
    column: 17,
    category: "dependent_file_cursor",
    note: "readdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1503,
    column: 7,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1563,
    column: 5,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1670,
    column: 7,
    category: "ordered_protocol_emission",
    note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1696,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitGatedInventoryStream(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 2012,
    column: 29,
    category: "dependent_file_cursor",
    note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 2035,
    column: 31,
    category: "dependent_file_cursor",
    note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 2121,
    column: 27,
    category: "dependent_file_cursor",
    note: "scanChildSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/claude_code/index.ts",
    line: 1651,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitDerivedCoverage(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/claude_code/integration.test.ts",
    line: 83,
    column: 5,
    category: "test_assertion_sequencing",
    note: "processJsonlLine(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/local-jsonl-incremental.test.ts",
    line: 378,
    column: 8,
    category: "test_assertion_sequencing",
    note: "import(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/claude_code/local-jsonl-incremental.test.ts",
    line: 834,
    column: 20,
    category: "test_assertion_sequencing",
    note: "makeAttachmentSource(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/codex/index.ts",
    line: 510,
    column: 20,
    category: "dependent_file_cursor",
    note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 523,
    column: 7,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 542,
    column: 20,
    category: "dependent_file_cursor",
    note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 593,
    column: 11,
    category: "dependent_file_cursor",
    note: "isDirectoryPath(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1833,
    column: 5,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1889,
    column: 7,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 1950,
    column: 21,
    category: "ordered_protocol_emission",
    note: "resolveGatedInventoryRecords(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/index.ts",
    line: 2052,
    column: 5,
    category: "ordered_protocol_emission",
    note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/codex/rollout-stream.test.ts",
    line: 216,
    column: 7,
    category: "test_assertion_sequencing",
    note: "once(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/github/index.ts",
    line: 441,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 465,
    column: 5,
    category: "dependent_pagination",
    note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 540,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 562,
    column: 5,
    category: "dependent_pagination",
    note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 636,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 660,
    column: 5,
    category: "dependent_pagination",
    note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 903,
    column: 18,
    category: "ordered_protocol_emission",
    note: "emitPullRequestItem(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 940,
    column: 5,
    category: "dependent_pagination",
    note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 1023,
    column: 20,
    category: "dependent_pagination",
    note: "drainPrSearchWindow(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/github/index.ts",
    line: 1126,
    column: 5,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/github/index.ts",
    line: 1149,
    column: 5,
    category: "dependent_pagination",
    note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/gmail/integration.test.ts",
    line: 2073,
    column: 16,
    category: "test_assertion_sequencing",
    note: "run(): each run feeds the prior run's committed cursor into the next; the walk is the assertion",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 300,
    column: 9,
    category: "bounded_retry_polling",
    note: "checkSession(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 648,
    column: 23,
    category: "ordered_protocol_emission",
    note: "deps.hydrateAttachment(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 665,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 687,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 833,
    column: 25,
    category: "ordered_protocol_emission",
    note: "processMessage(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 1127,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 2100,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 2300,
    column: 18,
    category: "provider_pacing_backpressure",
    note: "processServedAttachmentRecoveryGap(): rate-limited/budget-gated external call",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 3235,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 776,
    column: 7,
    category: "ordered_protocol_emission",
    note: "uploadBodyBlob(): canonical field bytes must bind before their record is emitted",
  },
  {
    path: "connectors/gmail/index.ts",
    line: 3458,
    column: 26,
    category: "shared_mutable_accumulator",
    note: "runThreadsPass(): each range updates the shared fingerprint cursor and accumulated coverage count",
  },
  {
    path: "connectors/google_messages/index.ts",
    line: 662,
    column: 17,
    category: "dependent_pagination",
    note: "fetchChatMessages(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_messages/index.ts",
    line: 788,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_maps/archive-stream.test.ts",
    line: 157,
    column: 7,
    category: "dependent_file_cursor",
    note: "large-path oracle writes one ordered JSON array to a shared stream",
  },
  {
    path: "connectors/google_maps/archive-stream.ts",
    line: 697,
    column: 7,
    category: "ordered_protocol_emission",
    note: "drain(): sequential event callbacks preserve source order and backpressure",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 108,
    column: 5,
    category: "dependent_file_cursor",
    note: "walkDiscoveryDirectory(): sequential file/dir walk follows the discovered source boundary",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 131,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRequestedSkip(): ordered SKIP_RESULT protocol emission",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 239,
    column: 11,
    category: "ordered_protocol_emission",
    note: "processPointRecords(): ordered schema admission and point protocol emission",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 286,
    column: 11,
    category: "ordered_protocol_emission",
    note: "processSegmentRecords(): ordered schema admission and segment protocol emission",
  },
  {
    path: "connectors/google_maps/index.ts",
    line: 419,
    column: 5,
    category: "dependent_file_cursor",
    note: "loadExports(): sequential file progress follows the discovered source order",
  },
  {
    path: "connectors/google_maps_data_portability/index.ts",
    line: 267,
    column: 20,
    category: "dependent_pagination",
    note: "collectResourceGroup(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 120,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 170,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 220,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 323,
    column: 20,
    category: "dependent_file_cursor",
    note: "buildPhotoRecordForFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/google_takeout/index.ts",
    line: 502,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 282,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 698,
    column: 20,
    category: "ordered_browser_interaction",
    note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 646,
    column: 20,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 666,
    column: 9,
    category: "ordered_browser_interaction",
    note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 750,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/heb/index.ts",
    line: 860,
    column: 22,
    category: "ordered_browser_interaction",
    note: "loadListPage(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/heb/index.ts",
    line: 886,
    column: 7,
    category: "ordered_browser_interaction",
    note: "processListOrder(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/ical/index.ts",
    line: 56,
    column: 15,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/ical/index.ts",
    line: 76,
    column: 20,
    category: "ordered_protocol_emission",
    note: "fetchIcs(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ical/index.ts",
    line: 121,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ical/index.ts",
    line: 154,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitEventsFromSource(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 332,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 376,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/imessage/index.ts",
    line: 631,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "resolveAttachmentHydration(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/notion/index.ts",
    line: 201,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/notion/index.ts",
    line: 288,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/oura/index.ts",
    line: 149,
    column: 18,
    category: "dependent_pagination",
    note: "oura(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/oura/index.ts",
    line: 242,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/pocket/index.ts",
    line: 170,
    column: 21,
    category: "dependent_pagination",
    note: "fetchPocketPage(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/pocket/index.ts",
    line: 176,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 616,
    column: 20,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 331,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/reddit/index.ts",
    line: 462,
    column: 5,
    category: "dependent_pagination",
    note: "collectStream(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/reddit/integration.test.ts",
    line: 1182,
    column: 5,
    category: "test_assertion_sequencing",
    note: "collectStream(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/reddit/integration.test.ts",
    line: 1136,
    column: 5,
    category: "test_assertion_sequencing",
    note: "collectStream(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1496,
    column: 20,
    category: "shared_mutable_accumulator",
    note: "refreshScopedArchive(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1953,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1596,
    column: 9,
    category: "shared_mutable_accumulator",
    note: "runRequestedStreams(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1851,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1860,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 1855,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2101,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2165,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2526,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2550,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/signal/index.ts",
    line: 688,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitMessageRowsAndReactions(): emitRecord() Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/signal/index.ts",
    line: 709,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitReactionRowsFromMessages(): emitRecord() Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/signal/index.ts",
    line: 723,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitConversationRows(): emitRecord() Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/signal/index.ts",
    line: 957,
    column: 9,
    category: "dependent_file_cursor",
    note: "listExportedAttachmentFiles(): sequential recursive directory walk over sigtop's exported attachment tree",
  },
  {
    path: "connectors/signal/index.ts",
    line: 1029,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "resolveAttachmentHydration(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2558,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2566,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2607,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/slack/index.ts",
    line: 2985,
    column: 32,
    category: "dependent_file_cursor",
    note: "reclaimUploads(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/slack/slack-api.ts",
    line: 266,
    column: 18,
    category: "dependent_pagination",
    note: "slackApiPost(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/slack/slack-api.ts",
    line: 313,
    column: 18,
    category: "dependent_pagination",
    note: "slackApiGet(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 280,
    column: 5,
    category: "dependent_pagination",
    note: "paginate(): page progress follows the fetched page before advancing its cursor",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 283,
    column: 21,
    category: "shared_mutable_accumulator",
    note: "paginate(): fold accumulator from each item is the next iteration's input",
  },
  {
    path: "connectors/spotify/index.ts",
    line: 430,
    column: 5,
    category: "ordered_protocol_emission",
    note: "progress(): top-artist time-range windows report in-order before the next window starts",
  },
  {
    path: "connectors/strava/index.ts",
    line: 173,
    column: 7,
    category: "dependent_pagination",
    note: "progressWithSignals(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/strava/index.ts",
    line: 189,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/twitter_archive/index.ts",
    line: 146,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/credit-card-billing-stats.test.ts",
    line: 204,
    column: 5,
    category: "test_assertion_sequencing",
    note: "deps.emitRecord(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 328,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 474,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 779,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 844,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1162,
    column: 7,
    category: "ordered_browser_interaction",
    note: "page.goto(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1864,
    column: 21,
    category: "bounded_retry_polling",
    note: "runSingleLadderAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 1982,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2156,
    column: 5,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2365,
    column: 7,
    category: "ordered_protocol_emission",
    note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2600,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2639,
    column: 5,
    category: "ordered_protocol_emission",
    note: "processPdfStatementRow(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 2838,
    column: 9,
    category: "ordered_protocol_emission",
    note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 3173,
    column: 23,
    category: "ordered_browser_interaction",
    note: "navigateToCardOrGap(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/index.ts",
    line: 3195,
    column: 11,
    category: "ordered_protocol_emission",
    note: "emitCreditCardNavFailureGaps(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/usaa/integration.test.ts",
    line: 611,
    column: 21,
    category: "test_assertion_sequencing",
    note: "driveExport(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 221,
    column: 9,
    category: "ordered_browser_interaction",
    note: "c.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 244,
    column: 9,
    category: "ordered_browser_interaction",
    note: "c.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/statement-pdfs.ts",
    line: 657,
    column: 7,
    category: "ordered_browser_interaction",
    note: "hydrateOneStatement(): sequential Playwright action against the shared page/context",
  },
  {
    path: "connectors/usaa/transactions-coverage.test.ts",
    line: 178,
    column: 7,
    category: "test_assertion_sequencing",
    note: "deps.emit(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "connectors/venmo/index.ts",
    line: 265,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/venmo/index.ts",
    line: 314,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/venmo/index.ts",
    line: 344,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/venmo/index.ts",
    line: 426,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/whatsapp/chat-identity-reconciliation.test.ts",
    line: 190,
    column: 26,
    category: "test_assertion_sequencing",
    note: "runImport(): test drives/asserts an ordered per-case side effect (each run's STATE cursor is threaded into the next run to prove the per-identityKey alias cap accumulates and plateaus correctly across 25 sequential imports)",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 161,
    column: 9,
    category: "dependent_file_cursor",
    note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 754,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "buildAttachmentRecord(): rate-limited/budget-gated blob-upload call (wraps uploadBlob())",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 1141,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitStateForCursor(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/whatsapp/index.ts",
    line: 1204,
    column: 39,
    category: "dependent_file_cursor",
    note: "parseExportFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/whoop/index.ts",
    line: 226,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): sleep records must preserve source and protocol order",
  },
  {
    path: "connectors/whoop/index.ts",
    line: 231,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): workout records must preserve source and protocol order",
  },
  {
    path: "connectors/whoop/index.ts",
    line: 260,
    column: 62,
    category: "provider_pacing_backpressure",
    note: "fetchPath(): bounded WHOOP history windows stay sequential to avoid provider pressure",
  },
  {
    path: "connectors/whoop/index.ts",
    line: 262,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitAggregateRecord(): records preserve WHOOP window order before cursor state",
  },
  {
    path: "connectors/whoop/index.ts",
    line: 269,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emit(): stream cursor state follows all covered WHOOP records",
  },
  {
    path: "connectors/whatsapp/txt-toctou.test.ts",
    line: 48,
    column: 7,
    category: "test_assertion_sequencing",
    note: "waitForBarrier(): test waits for the fixture writer's ordered filesystem barrier",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 933,
    column: 9,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1113,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1119,
    column: 9,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1192,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1286,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1390,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1501,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1594,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1695,
    column: 5,
    category: "dependent_pagination",
    note: "progress(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1710,
    column: 7,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 1843,
    column: 5,
    category: "ordered_protocol_emission",
    note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/ynab/index.ts",
    line: 2075,
    column: 19,
    category: "dependent_pagination",
    note: "collectForBudget(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "src/adaptive-lane.ts",
    line: 428,
    column: 24,
    category: "bounded_retry_polling",
    note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/amazon.ts",
    line: 66,
    column: 15,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/amazon.ts",
    line: 69,
    column: 11,
    category: "ordered_browser_interaction",
    note: "el.isVisible(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/chase.ts",
    line: 179,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 393,
    column: 7,
    category: "ordered_browser_interaction",
    note: "candidate.waitFor(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 583,
    column: 5,
    category: "bounded_retry_polling",
    note: "checkpoint(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/chatgpt.ts",
    line: 935,
    column: 5,
    category: "bounded_retry_polling",
    note: "page.waitForTimeout(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 1553,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 1602,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 1669,
    column: 7,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.test.ts",
    line: 1698,
    column: 16,
    category: "test_assertion_sequencing",
    note: "ensureHebSession(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 116,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 135,
    column: 19,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 138,
    column: 34,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 159,
    column: 19,
    category: "ordered_browser_interaction",
    note: "locator.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 162,
    column: 34,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 188,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 222,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 256,
    column: 38,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 468,
    column: 21,
    category: "ordered_browser_interaction",
    note: "inspectPostSubmitAuthSurface(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 637,
    column: 20,
    category: "ordered_browser_interaction",
    note: "fillWhenUsable(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 651,
    column: 40,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/heb.ts",
    line: 903,
    column: 22,
    category: "bounded_retry_polling",
    note: "waitForUniqueVerificationCodeFormRoot(): retry/poll until the remounted OTP surface is uniquely actionable",
  },
  {
    path: "src/auto-login/manual-action-copy.test.ts",
    line: 42,
    column: 17,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/auto-login/reddit.test.ts",
    line: 134,
    column: 9,
    category: "bounded_retry_polling",
    note: "makeLocator().waitFor(): bounded test double polling until the simulated locator attaches",
  },
  {
    path: "src/auto-login/reddit.ts",
    line: 396,
    column: 9,
    category: "bounded_retry_polling",
    note: "isSessionLiveWithRetry(): bounded post-manual-handoff re-probe — don't trust a single isSessionLive check right after the owner's continue click",
  },
  {
    path: "src/auto-login/reddit.ts",
    line: 669,
    column: 19,
    category: "bounded_retry_polling",
    note: "hasSessionCookie(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/auto-login/reddit.ts",
    line: 567,
    column: 7,
    category: "ordered_protocol_emission",
    note: "drainProbeTimeouts(): probe-timeout checkpoints must reach the runtime watchdog in the order they were observed",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 174,
    column: 19,
    category: "ordered_browser_interaction",
    note: "action.count(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 179,
    column: 18,
    category: "ordered_browser_interaction",
    note: "locator.isVisible(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/usaa.ts",
    line: 347,
    column: 18,
    category: "bounded_retry_polling",
    note: "requestOtp(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/browser-launch.ts",
    line: 516,
    column: 14,
    category: "bounded_retry_polling",
    note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/browser-launch.ts",
    line: 938,
    column: 24,
    category: "dependent_file_cursor",
    note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/browser-launch.ts",
    line: 1008,
    column: 16,
    category: "shared_mutable_accumulator",
    note: "closeRemoteDevToolsTarget(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/browser-launch.ts",
    line: 1016,
    column: 27,
    category: "shared_mutable_accumulator",
    note: "fetchRemoteDevToolsTargets(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/collector-registry.test.ts",
    line: 53,
    column: 33,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/collector-registry.test.ts",
    line: 70,
    column: 33,
    category: "test_assertion_sequencing",
    note: "readFile(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 279,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 302,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-http-governor.test.ts",
    line: 348,
    column: 5,
    category: "test_assertion_sequencing",
    note: "g1.request(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-runtime-session-watchdog.test.ts",
    line: 152,
    column: 7,
    category: "test_assertion_sequencing",
    note: "watchdog.checkpoint(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/connector-runtime.ts",
    line: 1477,
    column: 9,
    category: "shared_mutable_accumulator",
    note: "closeBrowserPage(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/interaction-handler.ts",
    line: 84,
    column: 7,
    category: "dependent_file_cursor",
    note: "access(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/interaction-handler.ts",
    line: 119,
    column: 21,
    category: "bounded_retry_polling",
    note: "promptStdin(): retry/backoff/poll loop gated on the prior attempt's outcome",
  },
  {
    path: "src/local-device-runtime.ts",
    line: 262,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "queue.enqueue(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/local-device-runtime.ts",
    line: 326,
    column: 18,
    category: "shared_mutable_accumulator",
    note: "input.queue.dequeueReady(): loop body mutates a shared accumulator the next iteration reads",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 81,
    column: 27,
    category: "dependent_file_cursor",
    note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 182,
    column: 29,
    category: "dependent_file_cursor",
    note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/local-jsonl-cursor.ts",
    line: 193,
    column: 9,
    category: "dependent_file_cursor",
    note: "onLine(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/profile-lock.ts",
    line: 132,
    column: 7,
    category: "dependent_file_cursor",
    note: "fs.unlink(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "src/reference-blob-uploader.test.ts",
    line: 39,
    column: 12,
    category: "test_assertion_sequencing",
    note: "reader.read(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/reference-blob-uploader.test.ts",
    line: 103,
    column: 5,
    category: "test_assertion_sequencing",
    note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
  },
  {
    path: "src/scheduler-runner.ts",
    line: 253,
    column: 7,
    category: "devtool_sequential_output",
    note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
  },
  {
    path: "connectors/apple_contacts/bounded-response-read.ts",
    line: 86,
    column: 31,
    category: "dependent_file_cursor",
    note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/apple_contacts/carddav-client.ts",
    line: 87,
    column: 41,
    category: "dependent_pagination",
    note: "davRequest(): next redirect hop depends on the prior response's Location header",
  },
  {
    path: "connectors/apple_contacts/carddav-client.ts",
    line: 398,
    column: 17,
    category: "provider_pacing_backpressure",
    note: "addressbookMultiget(): sequential bounded chunks so one change set cannot issue an unbounded parallel fan-out at the provider",
  },
  {
    path: "connectors/apple_contacts/discovery.ts",
    line: 251,
    column: 17,
    category: "dependent_pagination",
    note: "propfindFollowingRedirects(): next redirect hop depends on the prior response's Location header",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 562,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 586,
    column: 9,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 606,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 417,
    column: 7,
    category: "ordered_protocol_emission",
    note: "hydrateMissingBodies(): emitContactRecord() Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 375,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/apple_contacts/index.ts",
    line: 780,
    column: 13,
    category: "shared_mutable_accumulator",
    note: "collectAddressBook(): loop body mutates a shared bookCursor/newState accumulator the next iteration reads",
  },
  {
    path: "connectors/google_calendar/api.ts",
    line: 210,
    column: 29,
    category: "dependent_pagination",
    note: "listCalendars(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 168,
    column: 18,
    category: "dependent_pagination",
    note: "pageThroughEvents(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 184,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 271,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_calendar/index.ts",
    line: 295,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "collectGoogleCalendar(): loop body mutates a shared nextEventsState accumulator the next iteration reads",
  },
  {
    path: "connectors/google_contacts/api.ts",
    line: 289,
    column: 29,
    category: "dependent_pagination",
    note: "listContactGroups(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 165,
    column: 18,
    category: "dependent_pagination",
    note: "syncPeoplePages(): next request depends on the prior page's cursor/offset/response",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 177,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/google_contacts/index.ts",
    line: 258,
    column: 9,
    category: "ordered_protocol_emission",
    note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 320,
    column: 29,
    category: "dependent_file_cursor",
    note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 703,
    column: 17,
    category: "provider_pacing_backpressure",
    note: "normalizeOneAttachment(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 844,
    column: 5,
    category: "dependent_pagination",
    note: "fetchPaginatedList(): next request depends on the prior page's page-number cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1223,
    column: 20,
    category: "provider_pacing_backpressure",
    note: "emitInScopeGroupMessages(): toGroupMessageRecord() rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1279,
    column: 5,
    category: "dependent_pagination",
    note: "collectGroupMessagesForwardFromCursor(): next request depends on the prior page's after_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1406,
    column: 5,
    category: "dependent_pagination",
    note: "collectGroupMessagesBackwardToNaturalEnd(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1665,
    column: 11,
    category: "ordered_protocol_emission",
    note: 'emitRecord("groups"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1698,
    column: 11,
    category: "ordered_protocol_emission",
    note: 'emitRecord("direct_messages"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1767,
    column: 5,
    category: "dependent_pagination",
    note: "collectDirectChatMessagesForChat(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1795,
    column: 22,
    category: "provider_pacing_backpressure",
    note: "toDirectChatMessageRecord(): rate-limited/budget-gated blob-upload call",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 1842,
    column: 28,
    category: "shared_mutable_accumulator",
    note: "collectDirectChatMessages(): loop body mutates a shared considered accumulator the next iteration reads",
  },
  {
    path: "connectors/groupme/index.ts",
    line: 2142,
    column: 29,
    category: "shared_mutable_accumulator",
    note: "collectGroupMessages(): loop body mutates shared considered/nextCursors accumulators the next iteration reads",
  },
  {
    path: "connectors/groupme/incremental-frontier.test.ts",
    line: 413,
    column: 19,
    category: "test_assertion_sequencing",
    note: "cappedForwardWalk(): deliberately reimplements a page-capped pagination loop to prove the >old-cap discriminator test actually fails under the old (removed) cap — sequential by design, not production code",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 887,
    column: 5,
    category: "shared_mutable_accumulator",
    note: "collectItems(): loop body mutates shared state.items/totalItemsEmitted accumulator the next iteration reads",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 946,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitErrorSkipResults(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 200,
    column: 31,
    category: "dependent_file_cursor",
    note: "readBodyWithStreamingCap(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 774,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'emitRecord("libraries"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 815,
    column: 23,
    category: "dependent_pagination",
    note: "collectItemsForLibrary(): next request depends on the prior page's StartIndex cursor",
  },
  {
    path: "connectors/jellyfin/index.ts",
    line: 847,
    column: 7,
    category: "ordered_protocol_emission",
    note: 'emitRecord("items"): Collection Profile protocol emission requiring in-order delivery',
  },
  {
    path: "connectors/netflix_export/index.ts",
    line: 306,
    column: 5,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "connectors/netflix_export/parsers.ts",
    line: 163,
    column: 29,
    category: "dependent_file_cursor",
    note: "fd.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
  },
  {
    path: "connectors/steam/index.ts",
    line: 456,
    column: 7,
    category: "ordered_protocol_emission",
    note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
  },
  {
    path: "src/auto-login/venmo.test.ts",
    line: 787,
    column: 11,
    category: "bounded_retry_polling",
    note: "makeTwoStepVenmoPage(): fake Locator.waitFor() polls its own deadline, mirroring Playwright's real wait semantics",
  },
  {
    path: "src/auto-login/venmo.test.ts",
    line: 1494,
    column: 9,
    category: "test_assertion_sequencing",
    note: "ensureVenmoSession(): test drives an ordered retry-if-retryable dispatch simulation",
  },
  {
    path: "src/auto-login/venmo.ts",
    line: 604,
    column: 32,
    category: "ordered_browser_interaction",
    note: "Promise.all(): sequential Playwright action against the shared page/context",
  },
  {
    path: "src/auto-login/venmo.ts",
    line: 647,
    column: 9,
    category: "ordered_browser_interaction",
    note: "clickVenmoLoginSubmit(): submit-control candidates tried in priority order; must stop at the first visible one, since clicking a second control would submit the form twice",
  },
];
