// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/* RECORDROOM — Explore/Sources fixtures. Models the real shape of a
   personal server: connection INSTANCES are the unit of identity (two
   Gmails with different configs, two Claude Codes on different machines),
   stream names overlap incidentally, records carry full fields and
   relationships, some fields are images. Fictional persona data. */
window.RRX = {
  now: "2026-06-12",
  totalOnServer: "48,120",
  days: [
    ["2026-06-12", "Fri, Jun 12"],
    ["2026-06-11", "Thu, Jun 11"],
    ["2026-06-10", "Wed, Jun 10"],
  ],
  spark: [2, 1, 3, 2, 1, 2, 4, 3, 2, 1, 2, 3, 5, 4, 3, 2, 4, 6, 5, 7, 6, 8, 7, 9, 8, 10, 12, 9, 11, 16],

  connections: [
    {
      id: "cdx",
      name: "Codex CLI — laptop",
      kind: "codex",
      status: "active",
      cin: "cin_cdx_91ad02",
      account: "local agent · stdio bridge",
      config: "full session capture",
      added: "2026-02-11",
      auth: "device-bound key",
      schedule: "live",
      lastRun: "streaming",
      streams: [
        { name: "sessions", records: "1,204", cursor: "live", searchable: true, last: "7 min ago" },
        { name: "messages", records: "18,440", cursor: "live", searchable: true, last: "22 min ago" },
        { name: "function_calls", records: "22,901", cursor: "live", searchable: false, last: "22 min ago" },
      ],
    },
    {
      id: "cc1",
      name: "Claude Code — MacBook",
      kind: "claude-code",
      status: "active",
      cin: "cin_cc_77b210",
      account: "local agent · MacBook",
      config: "sessions + messages + attachments",
      added: "2026-01-08",
      auth: "device-bound key",
      schedule: "live",
      lastRun: "streaming",
      streams: [
        { name: "sessions", records: "312", cursor: "live", searchable: true, last: "20 h ago" },
        { name: "messages", records: "4,180", cursor: "live", searchable: true, last: "20 h ago" },
        { name: "attachments", records: "96", cursor: "live", searchable: false, last: "3 d ago" },
        { name: "skills", records: "14", cursor: "live", searchable: true, last: "9 d ago" },
      ],
    },
    {
      id: "cc2",
      name: "Claude Code — build VM",
      kind: "claude-code",
      status: "revoked",
      cin: "cin_cc_2a96ef",
      account: "local agent · build VM",
      config: "sessions + messages",
      added: "2026-03-02",
      auth: "revoked May 28",
      schedule: "—",
      lastRun: "refused (revoked)",
      streams: [
        { name: "sessions", records: "88", cursor: "frozen May 28", searchable: true, last: "May 28" },
        { name: "messages", records: "1,402", cursor: "frozen May 28", searchable: true, last: "May 28" },
        { name: "attachments", records: "12", cursor: "frozen May 28", searchable: false, last: "May 24" },
        { name: "skills", records: "6", cursor: "frozen May 28", searchable: true, last: "May 12" },
      ],
    },
    {
      id: "gm1",
      name: "Gmail — personal",
      kind: "gmail",
      status: "active",
      cin: "cin_gm_410c2b",
      account: "m.okafor@gmail.example",
      config: "all mail · bodies + attachments",
      added: "2025-11-20",
      auth: "oauth refresh ok",
      schedule: "every 15 min",
      lastRun: "ok · 31 min ago",
      streams: [
        { name: "messages", records: "31,007", cursor: "→ 14:28Z", searchable: true, last: "31 min ago" },
        { name: "threads", records: "12,884", cursor: "→ 14:28Z", searchable: true, last: "31 min ago" },
        { name: "message_bodies", records: "30,910", cursor: "→ 14:28Z", searchable: true, last: "31 min ago" },
        { name: "attachments", records: "2,114", cursor: "→ 13:02Z", searchable: false, last: "2 h ago" },
      ],
    },
    {
      id: "gm2",
      name: "Gmail — work (filtered)",
      kind: "gmail",
      status: "active",
      cin: "cin_gm_88e1f0",
      account: "m.okafor@acme.example",
      config: "label:receipts + label:travel only",
      added: "2026-04-02",
      auth: "oauth refresh ok",
      schedule: "hourly",
      lastRun: "ok · 50 min ago",
      streams: [
        { name: "messages", records: "1,201", cursor: "→ 14:10Z", searchable: true, last: "20 h ago" },
        { name: "threads", records: "884", cursor: "→ 14:10Z", searchable: true, last: "20 h ago" },
        { name: "attachments", records: "310", cursor: "→ 14:10Z", searchable: false, last: "20 h ago" },
      ],
    },
    {
      id: "gh",
      name: "GitHub — mokafor",
      kind: "github",
      status: "active",
      cin: "cin_gh_53aa19",
      account: "github.com/mokafor",
      config: "repos + daily stats",
      added: "2026-01-15",
      auth: "fine-grained token ok",
      schedule: "hourly",
      lastRun: "ok · 23 min ago",
      streams: [
        { name: "repositories", records: "41", cursor: "→ 14:40Z", searchable: true, last: "23 min ago" },
        { name: "user_stats", records: "365", cursor: "→ today", searchable: false, last: "15 h ago" },
      ],
    },
    {
      id: "cg",
      name: "ChatGPT — personal",
      kind: "chatgpt",
      status: "active",
      cin: "cin_cg_b042d8",
      account: "everyone@okafor.example",
      config: "conversations + messages",
      added: "2026-02-28",
      auth: "session export ok",
      schedule: "daily · 06:00Z",
      lastRun: "ok · 9 h ago",
      streams: [
        { name: "conversations", records: "871", cursor: "→ 06-12", searchable: true, last: "2 h ago" },
        { name: "messages", records: "12,030", cursor: "→ 06-12", searchable: true, last: "2 h ago" },
      ],
    },
    {
      id: "fm",
      name: "First Meridian — checking",
      kind: "bank",
      status: "reauth",
      cin: "cin_fm_206b11",
      account: "checking ····4417",
      config: "transactions + statements + balances",
      added: "2025-12-01",
      auth: "OFX session expired",
      schedule: "daily · 05:00Z",
      lastRun: "failed · 06-11",
      streams: [
        { name: "transactions", records: "41,203", cursor: "held at 06-10", searchable: true, last: "2 d ago" },
        { name: "statements", records: "72", cursor: "→ May", searchable: false, last: "12 d ago" },
        { name: "balances", records: "365", cursor: "held at 06-10", searchable: false, last: "2 d ago" },
      ],
    },
    {
      id: "nh",
      name: "Northstar HR",
      kind: "payroll",
      status: "active",
      cin: "cin_nh_e3391c",
      account: "employee 41880 · Acme Co",
      config: "pay + employment + tax docs",
      added: "2025-10-02",
      auth: "service token ok",
      schedule: "with payroll",
      lastRun: "ok · 33 min ago",
      streams: [
        { name: "pay_statements", records: "313", cursor: "→ Jun 12", searchable: true, last: "33 min ago" },
        { name: "employment", records: "4", cursor: "→ current", searchable: true, last: "4 d ago" },
        { name: "tax_docs", records: "12", cursor: "→ 2025", searchable: false, last: "Feb 02" },
      ],
    },
    {
      id: "tn",
      name: "Tonal",
      kind: "music",
      status: "active",
      cin: "cin_tn_77f024",
      account: "m.okafor",
      config: "listening history",
      added: "2026-01-30",
      auth: "oauth refresh ok",
      schedule: "every 15 min",
      lastRun: "ok · 12 min ago",
      streams: [{ name: "listening_history", records: "6,597", cursor: "→ 05:41Z", searchable: true, last: "9 h ago" }],
    },
  ],

  partial: {
    con: "cc2",
    revokedOn: "May 28",
    streams: ["sessions", "messages", "attachments", "skills"],
    raw: "RS /v1/streams/sessions/records → 400 connector_instance_inactive · req_b8d6ec07",
  },

  records: [
    /* ── Fri, Jun 12 ── */
    {
      id: "rec_cdx_s_0911",
      con: "cdx",
      stream: "sessions",
      day: "2026-06-12",
      rel: "7 min ago",
      title: "Pick up yesterday's auth review thread and summarize the open items…",
      fields: [
        ["prompt", "Pick up yesterday's auth review thread and summarize the open items…"],
        ["model", "gpt-5.5"],
        ["turns", "31"],
        ["started", "2026-06-12 14:48Z"],
      ],
    },
    {
      id: "rec_cdx_s_0910",
      con: "cdx",
      stream: "sessions",
      day: "2026-06-12",
      rel: "22 min ago",
      title: "Bounded task: implement admin management for the waitlist service…",
      links: [
        ["messages in session", "rec_cdx_m_4410"],
        ["tool calls", "rec_cdx_f_fold1"],
      ],
      fields: [
        ["prompt", "Bounded task: implement admin management for the waitlist service…"],
        ["model", "gpt-5.5 · low"],
        ["turns", "58"],
        ["started", "2026-06-12 14:21Z"],
      ],
    },
    {
      id: "rec_cdx_m_4410",
      con: "cdx",
      stream: "messages",
      day: "2026-06-12",
      rel: "22 min ago",
      role: "assistant",
      title: "All checks are green — build, tests, typecheck. PR is ready for review.",
      links: [["session", "rec_cdx_s_0910"]],
      fields: [
        ["role", "assistant"],
        ["session", "ses_a41"],
        ["chars", "212"],
        ["content", "All checks are green — build, tests, typecheck. PR is ready for review."],
      ],
    },
    {
      id: "rec_cdx_m_4409",
      con: "cdx",
      stream: "messages",
      day: "2026-06-12",
      rel: "22 min ago",
      role: "developer",
      degraded: true,
      title: "no text — tool turn",
      links: [["session", "rec_cdx_s_0910"]],
      fields: [
        ["role", "developer"],
        ["session", "ses_a41"],
        ["content", "— (tool output only)"],
      ],
    },
    {
      id: "rec_cdx_f_fold1",
      con: "cdx",
      stream: "function_calls",
      day: "2026-06-12",
      rel: "22 min ago",
      fold: 9,
      title: "9 tool calls in 4 minutes",
      snippet: "exec_command ×6 · write_stdin ×3",
      links: [["session", "rec_cdx_s_0910"]],
      fields: [
        ["calls", "9"],
        ["span", "4 min"],
        ["breakdown", "exec_command ×6 · write_stdin ×3"],
        ["session", "ses_a41"],
      ],
    },
    {
      id: "rec_gh_r_0182",
      con: "gh",
      stream: "repositories",
      day: "2026-06-12",
      rel: "23 min ago",
      title: "recordroom",
      fields: [
        ["repo", "mokafor/recordroom"],
        ["visibility", "private"],
        ["pushed", "2026-06-12 14:39Z"],
        ["open_prs", "2"],
      ],
    },
    {
      id: "rec_gm1_t_2210",
      con: "gm1",
      stream: "threads",
      day: "2026-06-12",
      rel: "31 min ago",
      title: "Your June 12 pay is on its way",
      links: [
        ["message", "rec_gm1_m_5121"],
        ["body", "rec_gm1_b_5121"],
      ],
      fields: [
        ["subject", "Your June 12 pay is on its way"],
        ["messages", "1"],
        ["participants", "payroll@northstar-hr.example"],
      ],
    },
    {
      id: "rec_gm1_m_5121",
      con: "gm1",
      stream: "messages",
      day: "2026-06-12",
      rel: "31 min ago",
      degraded: true,
      title: "no subject",
      snippet: "received 14:28Z · from payroll@northstar-hr.example",
      links: [
        ["thread", "rec_gm1_t_2210"],
        ["body", "rec_gm1_b_5121"],
      ],
      fields: [
        ["from", "payroll@northstar-hr.example"],
        ["received", "2026-06-12 14:28Z"],
        ["subject", "—"],
        ["size", "12 KB"],
      ],
    },
    {
      id: "rec_gm1_b_5121",
      con: "gm1",
      stream: "message_bodies",
      day: "2026-06-12",
      rel: "31 min ago",
      degraded: true,
      title: "message body · utf-8 · 38 KB",
      links: [
        ["message", "rec_gm1_m_5121"],
        ["thread", "rec_gm1_t_2210"],
      ],
      fields: [
        ["charset", "utf-8"],
        ["bytes", "38,114"],
        ["message_ref", "rec_gm1_m_5121"],
        ["text", "Hi M. — your pay for the period ending Jun 12 has been issued…"],
      ],
    },
    {
      id: "rec_ps_0313",
      con: "nh",
      stream: "pay_statements",
      day: "2026-06-12",
      rel: "33 min ago",
      title: "Acme Co · Jun 2026",
      snippet: "net $3,508.12",
      fields: [
        ["employer", "Acme Co"],
        ["period_start", "2026-06-01"],
        ["period_end", "2026-06-12"],
        ["gross_pay", "$5,210.00"],
        ["net_pay", "$3,508.12"],
        ["taxes_withheld", "$1,214.38"],
        ["benefits_detail", "401k 5% · health PPO"],
        ["bank_routing", "checking ····4417"],
      ],
    },
    {
      id: "rec_gh_r_0181",
      con: "gh",
      stream: "repositories",
      day: "2026-06-12",
      rel: "1 h ago",
      title: "pdpp-spec",
      fields: [
        ["repo", "mokafor/pdpp-spec"],
        ["visibility", "public"],
        ["pushed", "2026-06-12 14:02Z"],
        ["open_prs", "0"],
      ],
    },
    {
      id: "rec_cg_c_0871",
      con: "cg",
      stream: "conversations",
      day: "2026-06-12",
      rel: "2 h ago",
      title: "Summarize my May spending by category",
      fields: [
        ["title", "Summarize my May spending by category"],
        ["messages", "14"],
        ["model", "gpt-5.5"],
        ["started", "2026-06-12 12:40Z"],
      ],
    },
    {
      id: "rec_cdx_s_fold2",
      con: "cdx",
      stream: "sessions",
      day: "2026-06-12",
      rel: "3–11 h ago",
      fold: 4,
      title: "4 connector test pings",
      snippet: "\u201cReply with exactly: ok\u201d ×4",
      fields: [
        ["pings", "4"],
        ["span", "8 h"],
        ["prompt", "Reply with exactly: ok"],
      ],
    },
    {
      id: "rec_lh_6597",
      con: "tn",
      stream: "listening_history",
      day: "2026-06-12",
      rel: "9 h ago",
      title: "Hejira — Joni Mitchell",
      snippet: "kitchen speaker · 05:41Z",
      fields: [
        ["track", "Hejira"],
        ["artist", "Joni Mitchell"],
        ["played_at", "2026-06-12 05:41Z"],
        ["device", "kitchen speaker"],
        ["playlist_ref", "morning"],
      ],
    },
    {
      id: "rec_lh_6596",
      con: "tn",
      stream: "listening_history",
      day: "2026-06-12",
      rel: "9 h ago",
      title: "Pyramids — Frank Ocean",
      snippet: "kitchen speaker · 05:32Z",
      fields: [
        ["track", "Pyramids"],
        ["artist", "Frank Ocean"],
        ["played_at", "2026-06-12 05:32Z"],
        ["device", "kitchen speaker"],
        ["playlist_ref", "morning"],
      ],
    },
    {
      id: "rec_gh_u_0044",
      con: "gh",
      stream: "user_stats",
      day: "2026-06-12",
      rel: "15 h ago",
      degraded: true,
      title: "daily stats snapshot · 2026-06-12",
      fields: [
        ["date", "2026-06-12"],
        ["commits", "9"],
        ["prs_opened", "1"],
        ["reviews", "3"],
      ],
    },

    /* ── Thu, Jun 11 ── */
    {
      id: "rec_gm1_m_5108",
      con: "gm1",
      stream: "messages",
      day: "2026-06-11",
      rel: "16 h ago",
      title: "New sign-in detected on your hosting account",
      snippet: "Chrome on macOS · Tacoma, WA",
      fields: [
        ["from", "security@hosting.example"],
        ["subject", "New sign-in detected on your hosting account"],
        ["received", "2026-06-11 23:09Z"],
        ["size", "9 KB"],
      ],
    },
    {
      id: "rec_cc1_s_0392",
      con: "cc1",
      stream: "sessions",
      day: "2026-06-11",
      rel: "20 h ago",
      title: "Refactor the DS compiler's error messages for clarity…",
      links: [["messages in session", "rec_cc1_m_1840"]],
      fields: [
        ["prompt", "Refactor the DS compiler's error messages for clarity…"],
        ["model", "fable-4"],
        ["turns", "22"],
        ["started", "2026-06-11 19:02Z"],
      ],
    },
    {
      id: "rec_cc1_m_1840",
      con: "cc1",
      stream: "messages",
      day: "2026-06-11",
      rel: "20 h ago",
      role: "assistant",
      title: "Renamed the diagnostics — all 14 fixtures pass.",
      links: [["session", "rec_cc1_s_0392"]],
      fields: [
        ["role", "assistant"],
        ["session", "ses_c12"],
        ["chars", "148"],
        ["content", "Renamed the diagnostics — all 14 fixtures pass."],
      ],
    },
    {
      id: "rec_gm2_m_7011",
      con: "gm2",
      stream: "messages",
      day: "2026-06-11",
      rel: "20 h ago",
      title: "Receipt — storage unit autopay",
      snippet: "label:receipts · next payment 7/11",
      links: [["attachment", "rec_gm2_a_0310"]],
      fields: [
        ["from", "billing@extraspace.example"],
        ["subject", "Receipt — storage unit autopay"],
        ["label", "receipts"],
        ["received", "2026-06-11 19:40Z"],
        ["size", "640 KB"],
      ],
    },
    {
      id: "rec_gm2_a_0310",
      con: "gm2",
      stream: "attachments",
      day: "2026-06-11",
      rel: "20 h ago",
      image: true,
      title: "receipt-scan.jpg",
      snippet: "image/jpeg · 412 KB",
      links: [["message", "rec_gm2_m_7011"]],
      fields: [
        ["filename", "receipt-scan.jpg"],
        ["content_type", "image/jpeg"],
        ["bytes", "412,381"],
        ["message_ref", "rec_gm2_m_7011"],
      ],
    },
    {
      id: "rec_cg_m_3301",
      con: "cg",
      stream: "messages",
      day: "2026-06-11",
      rel: "20 h ago",
      role: "system",
      degraded: true,
      title: "no text — system turn",
      fields: [
        ["role", "system"],
        ["conversation", "cnv_864"],
        ["content", "—"],
      ],
    },
    {
      id: "rec_cg_c_0864",
      con: "cg",
      stream: "conversations",
      day: "2026-06-11",
      rel: "21 h ago",
      title: "Quick meatball recipes",
      fields: [
        ["title", "Quick meatball recipes"],
        ["messages", "6"],
        ["model", "gpt-5.5"],
        ["started", "2026-06-11 18:55Z"],
      ],
    },
    {
      id: "rec_gh_r_0179",
      con: "gh",
      stream: "repositories",
      day: "2026-06-11",
      rel: "22 h ago",
      title: "ds-compiler",
      fields: [
        ["repo", "mokafor/ds-compiler"],
        ["visibility", "private"],
        ["pushed", "2026-06-11 17:20Z"],
        ["open_prs", "1"],
      ],
    },
    {
      id: "rec_lh_6580",
      con: "tn",
      stream: "listening_history",
      day: "2026-06-11",
      rel: "1 d ago",
      title: "Both Sides Now — Joni Mitchell",
      snippet: "living room · 22:14Z",
      fields: [
        ["track", "Both Sides Now"],
        ["artist", "Joni Mitchell"],
        ["played_at", "2026-06-11 22:14Z"],
        ["device", "living room"],
        ["playlist_ref", "—"],
      ],
    },

    /* ── Wed, Jun 10 ── */
    {
      id: "rec_tx_41203",
      con: "fm",
      stream: "transactions",
      day: "2026-06-10",
      rel: "2 d ago",
      title: "Blue Bottle Coffee",
      snippet: "−$6.40 · coffee & cafes",
      fields: [
        ["date", "2026-06-10"],
        ["amount", "−$6.40"],
        ["merchant", "Blue Bottle Coffee"],
        ["category", "coffee & cafes"],
        ["account_ref", "checking ····4417"],
        ["memo", "card present"],
      ],
    },
    {
      id: "rec_tx_41202",
      con: "fm",
      stream: "transactions",
      day: "2026-06-10",
      rel: "2 d ago",
      title: "Rainier Grocery",
      snippet: "−$54.20 · groceries",
      fields: [
        ["date", "2026-06-10"],
        ["amount", "−$54.20"],
        ["merchant", "Rainier Grocery"],
        ["category", "groceries"],
        ["account_ref", "checking ····4417"],
        ["memo", "—"],
      ],
    },
    {
      id: "rec_tx_41195",
      con: "fm",
      stream: "transactions",
      day: "2026-06-10",
      rel: "2 d ago",
      title: "Hawthorne Property Mgmt",
      snippet: "−$1,850.00 · rent · june",
      fields: [
        ["date", "2026-06-10"],
        ["amount", "−$1,850.00"],
        ["merchant", "Hawthorne Property Mgmt"],
        ["category", "rent"],
        ["account_ref", "checking ····4417"],
        ["memo", "june"],
      ],
    },
    {
      id: "rec_cc1_s_0388",
      con: "cc1",
      stream: "sessions",
      day: "2026-06-10",
      rel: "2 d ago",
      title: "Sketch the consent ceremony copy variants…",
      fields: [
        ["prompt", "Sketch the consent ceremony copy variants…"],
        ["model", "fable-4"],
        ["turns", "9"],
        ["started", "2026-06-10 16:11Z"],
      ],
    },
    {
      id: "rec_gh_r_0175",
      con: "gh",
      stream: "repositories",
      day: "2026-06-10",
      rel: "2 d ago",
      title: "pdpp-explorer",
      fields: [
        ["repo", "mokafor/pdpp-explorer"],
        ["visibility", "public"],
        ["pushed", "2026-06-10 15:44Z"],
        ["open_prs", "0"],
      ],
    },
  ],
};
