import type { RecordsExplorerData } from "@pdpp/operator-ui/components/views/records-explorer-view";

const SNAPSHOT = "2026-07-01T12:10:00.000Z";

export function buildExploreDemoData(): RecordsExplorerData {
  return {
    activitySummary: {
      source: "exact_window",
      text: "Records over time · by day",
      total: 4,
    },
    bucketRequest: null,
    bucketSeries: null,
    connections: [
      {
        connectionId: "cin_demo_chatgpt_work",
        connectorId: "chatgpt",
        displayName: "ChatGPT work profile",
        streams: ["conversations", "messages"],
      },
      {
        connectionId: "cin_demo_amazon_home",
        connectorId: "amazon",
        displayName: "Amazon household archive",
        streams: ["orders", "order_items"],
      },
    ],
    cursorTrail: [],
    descriptor: {
      completeness: "exhaustive",
      cursor: "cursor_demo_next",
      has_more: true,
      kind: "complete_chronological",
      ordering: "time",
    },
    excludeConnectionIds: [],
    excludeStreams: [],
    feed: [
      {
        connectionDisplayName: "ChatGPT work profile",
        connectionId: "cin_demo_chatgpt_work",
        connectorId: "chatgpt",
        displayAt: "2026-07-01T11:58:00.000Z",
        displayIsSemantic: true,
        emittedAt: "2026-07-01T11:58:01.000Z",
        kind: "message",
        preview: {
          author: "Owner",
          body: "Summarize the connector health changes and flag anything that needs action.",
          kind: "message",
          title: "Owner asked about connector health",
        },
        recordId: "msg_demo_001",
        stream: "messages",
      },
      {
        connectionDisplayName: "Amazon household archive",
        connectionId: "cin_demo_amazon_home",
        connectorId: "amazon",
        displayAt: "2026-06-29T18:20:00.000Z",
        displayIsSemantic: true,
        emittedAt: "2026-06-29T20:57:21.000Z",
        kind: "generic",
        preview: {
          fields: [
            { label: "Order", name: "order_number", value: "D-1048" },
            { label: "Status", name: "status", value: "delivered" },
            { label: "Item count", name: "item_count", value: "3" },
          ],
          kind: "generic",
          title: "Demo order D-1048",
        },
        recordId: "ord_demo_1048",
        stream: "orders",
      },
      {
        connectionDisplayName: "ChatGPT work profile",
        connectionId: "cin_demo_chatgpt_work",
        connectorId: "chatgpt",
        displayAt: "2026-06-28T15:30:00.000Z",
        displayIsSemantic: true,
        emittedAt: "2026-06-28T15:30:01.000Z",
        kind: "message",
        preview: {
          author: "Assistant",
          body: "The source actionability model should render one owner action, not three duplicate rows.",
          kind: "message",
          title: "Assistant response",
        },
        recordId: "msg_demo_002",
        stream: "messages",
      },
    ],
    fromSearch: false,
    hybridUsed: false,
    lens: "recent",
    newSinceAnchor: 2,
    nextCursor: "cursor_demo_next",
    peek: {
      bodyJson: JSON.stringify(
        {
          author: "Owner",
          content: "Summarize the connector health changes and flag anything that needs action.",
          conversation_id: "conv_demo_atlas",
          created_at: "2026-07-01T11:58:00.000Z",
        },
        null,
        2
      ),
      connectionDisplayName: "ChatGPT work profile",
      connectionId: "cin_demo_chatgpt_work",
      connectorId: "chatgpt",
      emittedAt: "2026-07-01T11:58:01.000Z",
      error: null,
      fields: [
        { name: "author", state: "visible", type: "string", valueJson: JSON.stringify("Owner") },
        {
          name: "content",
          state: "visible",
          type: "string",
          valueJson: JSON.stringify("Summarize the connector health changes and flag anything that needs action."),
        },
        {
          name: "conversation_id",
          state: "visible",
          type: "string",
          valueJson: JSON.stringify("conv_demo_atlas"),
        },
      ],
      readUrl: "/v1/records/chatgpt/messages/msg_demo_001",
      recordId: "msg_demo_001",
      semanticTimestamp: { label: "created at", value: "2026-07-01T11:58:00.000Z" },
      stream: "messages",
    },
    query: "",
    searchHasMore: false,
    searchNextCursor: null,
    searchSort: "relevance",
    selectedConnectionIds: [],
    selectedStreams: [],
    serverFilterableFields: ["author", "status"],
    since: "",
    snapshotAnchor: SNAPSHOT,
    streamDoor: null,
    streamSeeAllLinks: [
      {
        connectionId: "cin_demo_chatgpt_work",
        connectorId: "chatgpt",
        displayName: "ChatGPT work profile",
        stream: "messages",
        total: 133_848,
      },
      {
        connectionId: "cin_demo_amazon_home",
        connectorId: "amazon",
        displayName: "Amazon household archive",
        stream: "orders",
        total: 1183,
      },
    ],
    supportsTimelineDirection: true,
    truncated: true,
    until: "",
    upcoming: [
      {
        connectionDisplayName: "Calendar Demo",
        connectionId: "cin_demo_calendar",
        connectorId: "calendar",
        displayAt: "2026-07-03T16:00:00.000Z",
        displayIsSemantic: true,
        emittedAt: "2026-07-01T12:00:00.000Z",
        kind: "event",
        preview: {
          body: "Review connector source-actionability packet.",
          eventTime: "4:00 PM",
          kind: "event",
          title: "Review owner console packet",
        },
        recordId: "evt_demo_001",
        stream: "events",
      },
    ],
    upcomingHasMore: false,
    upcomingNextCursor: null,
    upcomingTotal: 1,
    upcomingTrail: [],
    warnings: [
      {
        code: "partial_fan_in",
        message: "One demo source is hidden from this bounded preview; use the stream links for full-set reachability.",
      },
    ],
  };
}
