// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import {
  type ConceptColorTokenName,
  conceptColorTokenNames,
  conceptSchemes,
  defaultConceptSchemeName,
  resolveConceptScheme,
} from "../design-book/concept-colors.mts";

const SCHEME_NAME_PATTERN = /^[a-z][a-z0-9-]*$/;
const outputPath = fileURLToPath(
  new URL("../src/styles/surfaces/concept/tokens/generated-schemes.css", import.meta.url)
);
const schemeNamesOutputPath = fileURLToPath(
  new URL("../src/components/pdpp-concept/generated-color-scheme-names.ts", import.meta.url)
);

function renderDeclarations(tokens: Record<ConceptColorTokenName, string>): string {
  return conceptColorTokenNames.map((name) => `  --pdpp-concept-${name}: ${tokens[name]};`).join("\n");
}

function renderDefaultBlocks(): string[] {
  if (defaultConceptSchemeName === null) {
    return [];
  }

  const scheme = conceptSchemes.find((candidate) => candidate.name === defaultConceptSchemeName);
  assert.ok(scheme, `defaultConceptSchemeName "${defaultConceptSchemeName}" is not a declared scheme`);

  const light = renderDeclarations(resolveConceptScheme(scheme.light));
  const dark = renderDeclarations(resolveConceptScheme(scheme.dark));

  return [
    `/* Default scheme (${scheme.name}): overrides primitive.css on source order,\n * so no attribute is needed on <html> and the first paint never flashes. */\n:root {\n${light}\n}`,
    `:root[data-theme="dark"] {\n${dark}\n}`,
  ];
}

function render(): string {
  const blocks = conceptSchemes.flatMap((scheme) => {
    assert.match(scheme.name, SCHEME_NAME_PATTERN, `Invalid scheme name: ${scheme.name}`);
    const light = renderDeclarations(resolveConceptScheme(scheme.light));
    const dark = renderDeclarations(resolveConceptScheme(scheme.dark));

    return [
      `:root[data-pdpp-concept-scheme="${scheme.name}"] {\n${light}\n}`,
      `:root[data-theme="dark"][data-pdpp-concept-scheme="${scheme.name}"] {\n${dark}\n}`,
    ];
  });

  return `/* Copyright The PDP-Connect Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by \`pnpm colors:generate\`. Do not edit directly.
 * Named schemes are inert until data-pdpp-concept-scheme is set on <html>;
 * the default scheme is also emitted unqualified at the top of this file.
 */

${[...renderDefaultBlocks(), ...blocks].join("\n\n")}\n`;
}

function renderSchemeNames(): string {
  const names = conceptSchemes.map((scheme) => JSON.stringify(scheme.name)).join(", ");
  return `// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by \`pnpm colors:generate\`. Do not edit directly.

export const conceptColorSchemeNames = [${names}] as const;

export const defaultConceptColorSchemeName = ${JSON.stringify(defaultConceptSchemeName)} as const;
`;
}

async function main(): Promise<void> {
  const expected = render();
  const expectedSchemeNames = renderSchemeNames();

  if (process.argv.includes("--check")) {
    const [actual, actualSchemeNames] = await Promise.all([
      readFile(outputPath, "utf8").catch(() => ""),
      readFile(schemeNamesOutputPath, "utf8").catch(() => ""),
    ]);
    assert.equal(actual, expected, "Generated concept colour scheme CSS is stale; run pnpm colors:generate");
    assert.equal(
      actualSchemeNames,
      expectedSchemeNames,
      "Generated concept colour scheme names are stale; run pnpm colors:generate"
    );
    return;
  }

  await Promise.all([writeFile(outputPath, expected), writeFile(schemeNamesOutputPath, expectedSchemeNames)]);
  console.log(`Generated ${conceptSchemes.length} concept colour scheme(s)`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
